== Presentación del Editor

Samuel Rundell (1762-1848) era un comerciante de lana que vivía en Liskeard,
un pequeño pueblo al suroeste de Inglaterra.
De joven era reconocido como un ministro de la Sociedad de Amigos (Cuáqueros),
de la que era miembro.
En el transcurso de un largo ministerio,
viajó con frecuencia y celebró reuniones en el condado de Cornwall donde residía,
y en ocasiones realizó viajes más largos al servicio de la verdad, visitando Escocia,
Irlanda y otros lugares; y asistió con frecuencia a la Reunión Anual en Londres.

A lo largo de su vida se esforzó particularmente,
por insistir en la necesidad de una experiencia real y viva de purificación interior,
mediante una obediencia sin reservas a la luz o Espíritu de Cristo que obra en el corazón.
Habiendo experimentado la efectiva operación del Espíritu en su propia alma,
deseaba enormemente ver esta doctrina de las Escrituras
sostenida tanto entre sus compañeros Cuáqueros,
como más ampliamente conocida entre los Cristianos sinceros de todas las denominaciones.

El libro que estás leyendo surgió de ese ferviente deseo,
y fue publicado por primera vez en 1834 cuando Rundell tenía 72
años. Esta edición ha sido mínima y cuidadosamente modernizada,
con el objetivo de hacer que esta valiosa obra sea
algo más accesible para los lectores de hoy,
sin cambiar el significado del autor, ni modernizar en exceso el lenguaje original.
Todas las notas de pie de página son de Rundell,
a menos que se etiqueten como Nota del Editor.

Jared Henderson

Septiembre, 2018
