== Introducción

Cuando miramos a nuestro alrededor y observamos cuántos credos y sistemas
conflictivos de Cristianismo se promueven activamente en el presente,
nuestras reflexiones sobre el tema deberían llevarnos a
apreciar apropiadamente los privilegios con los que,
por el amor y la misericordia divinos, somos favorecidos;
porque la Luz de Cristo ha sido dada para alumbrar nuestras mentes,
y las Sagradas Escrituras han sido puestas a nuestro alcance
para que nos remitamos a ellas para recibir instrucción.

En el sagrado registro se expone claramente la doctrina predicada por nuestro
Señor y Salvador Jesucristo sobre el tema de la redención y salvación del hombre.
Como no hay ningún otro tema de igual interés e importancia,
estas pocas páginas fueron escritas para señalar desde esa alta autoridad,
el camino por el que toda la humanidad puede llegar
al conocimiento de la verdad y ser salvada.
Ojalá que ellas, bajo la bendición divina,
no sólo sean el medio para convencer al Cristiano meramente
nominal del inminente peligro en el que se encuentra,
sino también para animar al creyente débil, pero sincero,
a mantener firme su "`grano`" de fe vivo (Mateo 17:20);
para que en medio de todos los conflictos con los que sea probado,
su confianza esté firmemente fijada en Aquel que es el "`poder de Dios,
y sabiduría de Dios`" (1 Corintios 1:24). Por la sujeción a Su mandamiento,
"`llevad mi yugo sobre vosotros,
y aprended de mí,`" y por el cumplimiento resultante de Su misericordiosa promesa,
"`y hallaréis descanso para vuestras almas`" (Mateo 11:29),
el creyente sincero será eventualmente capaz de adoptar el antiguo lenguaje:
"`Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida;
¿de quién he de atemorizarme?`"
(Salmo 27:1)
