== Capítulo I. Sobre la Conversión y la Regeneración

Cuando nuestro Señor Jesucristo se transfiguró en el monte,
la voz de la magnífica gloria dio testimonio de Él diciendo: "`Este es mi Hijo amado,
en quien tengo complacencia; a él oíd`" (Mateo 17:5; 2 Pedro 1:17). Él,
cuya doctrina se nos ordena oír, y por supuesto, reverentemente abrazar, declaró:

[quote.scripture]
____
"`(Juan 3:16) Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito,
para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.
(3:17) Porque no envió Dios a su Hijo al mundo para condenar al mundo,
sino para que el mundo sea salvo por él. (3:18) El que en él cree, no es condenado;
pero el que no cree, ya es condenado,
porque no ha creído en el nombre del unigénito Hijo de Dios.
(3:19) Y esta es la condenación; que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
(3:20) Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprobadas.
(3:21) Pero el que obra verdad, viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"^
footnote:[En el versículo 16 de la cita anterior,
se presenta la fe en el Hijo de Dios como necesaria para obtener la vida eterna.
En el versículo 18,
se describe la condenación como el resultado de la incredulidad en Su nombre.
En los versículos 19 y 20, se describe más específicamente la causa de la condenación,
declarando que consiste en no amar,
sino en aborrecer (lo que por supuesto incluye no creer en) la luz.
Por lo tanto, parece que en este pasaje tan importante de la Escritura,
__la luz__ debe ser considerada como la manifestación
espiritual del Hijo de Dios en el alma del hombre,
pues Cristo dijo:
"`Yo soy la luz del mundo`" (Juan 8:12). La luz también puede ser considerada como uno
de los atributos divinos que están incluidos en el nombre del Hijo de Dios.
Al adoptar este punto de vista,
no hay ninguna inconsistencia esencial en las diversas partes de la doctrina
de nuestro santo Redentor respecto al __objeto de la fe.__
Cristo, el siempre bendito Hijo de Dios, es el objeto de la fe salvadora.
Y esta fe, cuando surge por primera vez en el alma recién despertada, es muy pequeña,
incluso es comparada con "`un grano de mostaza`"--y sin embargo,
es suficiente para que sus humildes receptores puedan creer en
Cristo revelado en sus almas en Su manifestación como "`la luz.`"
Por la "`obediencia de fe,`" estos experimentan su aumento gradual
y llegan a ser capaces de creer en todos los demás oficios de gracia
de Cristo tal como se exponen en las Sagradas Escrituras,
si tienen acceso a ese registro sagrado.
Además, creer en "`la luz`" es un mandato expreso de nuestro Salvador en Juan 12:36.]
____

Mediante esta declaración altamente importante de nuestro santo Redentor,
es evidente que la salvación de Dios a través de Él,
no se limita a ninguna clase o porción particular de la humanidad;
porque Dios amó de tal manera al mundo que dio a Su Hijo unigénito "`para que el mundo
sea salvo por él.`" El Hijo de Dios '`gustó la muerte por todos`' (Hebreos 2:9),
y todos los que verdadera y efectivamente __creen en
Su nombre__ participan de Su salvación. Ahora bien,
el __nombre__ del Hijo de Dios en este y en muchos otros lugares del Nuevo Testamento,
parece significar o hacer referencia a Sus atributos divinos; a saber, Su poder, vida,
luz, etc.^
footnote:[Ver Concordancia de Cruden bajo "`Nombre`"; también la Apología de Barclay;
los Principios de Tuke; las Doctrinas de Bates,
las tres últimas bajo el artículo "`Bautismo.`"]
Y esta luz, al ser "`la vida`" de "`la Palabra`" (o Hijo de Dios), es la "`luz verdadera,
que alumbra a todo hombre que viene a este mundo`" (Juan 1:4-9).

Debido a que esta luz alumbra en los corazones de todos los hijos de los hombres, estos,
en ocasiones son reprendidos y condenados por el pecado, "`por cuanto todos pecaron,
y están destituidos de la gloria de Dios`" (Romanos 3:23).
A los que no rechazan esta luz se les permite ver el miserable
estado en el que se encuentran mientras no están regenerados,
pues están en esclavitud bajo el poder del pecado y manchados por su contaminación.
Profundamente humillados por esta visión de su propia y verdadera condición,
sus corazones se contristan, son llevados al arrepentimiento y se levanta el clamor:
"`Dios, sé propicio a mí,
pecador`" (Lucas 18:13). Al permanecer en paciente
sumisión bajo la operación del poder divino,
son preparados para recibir una manifestación incrementada de la luz de la Palabra,
o Espíritu de Cristo,
por la que la fe (que es su fruto y que en algún grado ha sido
previamente ejercitada) es entonces más plenamente confirmada.
Así avanza la obra de conversión en los que no rechazan la aparición de la luz,
la cual es el don gratuito o "`gracia`" de Dios (Tito
2:11). Mediante la operación de Su poder,
los ojos de los espiritualmente ciegos son abiertos en alguna medida,
y algo de verdadera sensibilidad les es impartida a sus almas.
Estos son llevados a sentir más profundamente el inestimable valor de un Salvador,
y al venir a Él en fe, por la atracción del amor de Dios,^
footnote:["`Ninguno puede venir a mí, si el Padre que me envió no lo trajere.`"
(Juan 6:44)]
son escogidos para experimentar el bautismo de Su Espíritu;
siendo testigos de la remisión de sus pecados pasados a través
de la sangre de Aquel que es "`la propiciación por los +++[+++pecados]
de todo el mundo`" (1 Juan 2:2). Los que caminan así en la luz de Cristo,
en "`la obediencia de fe,`" son capacitados, al igual que los creyentes de antaño,
a gloriarse "`en Dios por nuestro Señor Jesucristo,`" por quien recibieron "`la reconciliación`"
con Dios (Romanos 5:11). Al permanecer bajo el bautismo del Espíritu,
Su operación de limpieza progresa en sus corazones.
Sus motivaciones--los secretos manantiales a la acción--son
purificadas de la mezcla con el pecado,
incluso aquellas ocultas bajo un aspecto aparentemente genuino.
Este proceso es descrito en el lenguaje figurativo de las Escrituras,
como el bautismo "`con fuego`" (Lucas 3:16).

La paz y el gozo que satisfacen al alma que estos han encontrado
como resultado de creer y obedecer a la luz o Espíritu de Cristo,
los animan a seguir uniéndose a Sus manifestaciones.
Ellos no sólo someten sus palabras y acciones,
sino también los pensamientos y los deseos de sus corazones,
a Su justo escrutinio y decisión; de modo que todo pensamiento y deseo pecaminoso,
toda palabra ociosa y toda mala obra, son llevados a juicio.
En esta luz ven que al "`fuego purificador`" (Malaquías
3:2) le queda mucho más por hacer en sus corazones,
de lo que habían concebido anteriormente;
y se les hace conscientes de que este proceso purificador
debe ser soportado para que el egoísmo,
el orgullo y la altivez,
con todos los demás afectos y deseos malignos que el tentador
se esfuerza por excitar y fomentar en sus corazones,
sean completamente subyugados y obligados a darle lugar a la justicia, el amor,
la pureza, la mansedumbre y a la gentileza de Cristo.
En medio de sus muchas pruebas,
velando en oración y pacientemente esperando en el Señor en el espíritu,
reciben un incremento de fuerza y son capacitados para mantenerse en el camino.
Al continuar en pos de la luz de Cristo, en __la senda de la negación a sí mismos,
tomando la cruz cada día__ (Lucas 9:23), no conformándose a las vanas costumbres,
modas y máximas de este mundo, ni fijando sus afectos en las riquezas o placeres de este,
sino apartándose y evitando todo lo que la luz manifiesta que es malo,
estos gradualmente experimentan el progreso del __nuevo nacimiento__ en sus almas;
todas las cosas viejas pasan y todas son hechas nuevas
(2 Corintios 5:17). La era del corazón,
figurativamente hablando,
es limpiada y la paja quemada en el '`fuego que nunca se apaga`'
(Mateo 3:12). Habiendo recibido así a Cristo Jesús el Señor,
Él les da "`potestad de ser hechos hijos de Dios,`" al ser dispensada
esta gracia "`a los que creen en __Su nombre__`" (Juan 1:12).

La descripción anterior del comienzo y progreso de conversión,
no pretende ser una norma exacta de los pasos por los que es conducido __cada individuo,__
en quien esta importante obra ha sido realizada.
El grado de depravación que ha manchado el carácter del ser humano antes de la conversión,
es mucho más grande en algunos casos que en otros.
También,
la repugnancia de la disposición natural a someterse
al control y guía de la luz de Cristo,
y colocarse así bajo Su yugo, varía mucho en las diferentes personas; en consecuencia,
puede ser necesario que Dios haga una variación correspondiente
en la duración e intensidad del "`fuego del purificador.`"
Y cuando los individuos de disposición seria han abrazado doctrinas
que los han llevado a poner hincapié en formas y ceremonias externas,
y que de hecho obstruyen su acercamiento a Cristo,
sus prejuicios no son fácilmente vencidos;
estos tienen que pasar por un tiempo de despojo--de romper en pedazos todas esas cosas,
por muy estimadas que sean,
que tienen la tendencia a impedir que reciban a Cristo en la sencillez
y humildad de los niños pequeños (Mateo 18:3). Puede esperarse,
entonces, ante esta gran diversidad de caracteres,
que en el proceso de conversión haya "`diversidad de operaciones,
pero es el mismo Dios el que hace todas las cosas en todos.`"
(1 Corintios 12:6).

La anterior consideración de la fe en el nombre del Hijo de Dios,
parece haber sido _expuesta por Él,_
en la última parte de ese memorable pasaje de las Escrituras,
con el que se inició este capítulo.
Después de que nuestro santo Redentor declaró: "`El que no cree, ya ha sido condenado,
porque no ha creído en el nombre del unigénito Hijo de Dios`" (Juan 3:18);
procedió a señalar aún más particularmente la __causa__
de la condenación. Pues inmediatamente agregó:

[quote.scripture, , Juan 3:19-21]
____
"`Y esta es la condenación: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprendidas.
Mas el que practica la verdad viene a la luz,
para que sea manifiesto que sus obras son hechas en Dios.`"
____

De estas palabras de nuestro bendito Salvador puede deducirse,
que aunque los profesantes Cristianos sean muy diligentes en adquirir
conocimiento literal de las doctrinas contenidas en las Sagradas Escrituras,
y profesen una ilimitada confianza en los beneficios resultantes
de los sufrimientos y muerte de nuestro Señor Jesucristo,
si persisten en desatender y rechazar las amonestaciones de la luz,
(que a veces brilla en sus corazones para liberarlos del poder
del pecado y limpiarlos de su contaminación) según Su doctrina,
__no creen en Su nombre__ verdaderamente, y en consecuencia,
permanecen en estado de condenación. Sería, en efecto,
un lamentable y peligroso engaño que personas como estas concluyeran,
que aunque permanezcan en estado de incredulidad y desobediencia,
son limpiadas y justificadas por la sangre de Cristo,
simplemente porque profesan una fe en Su aparición personal,
en Sus sufrimientos y en Su muerte.

En el texto citado arriba, el Salvador del mundo, brevemente,
pero en lenguaje claro y enfático, __predicó la doctrina de la luz;__
mostrando que ese don divino es abrazado y seguido por todo
aquel que "`hace`" o camina en la senda de "`la verdad`";
y que es aborrecido por todo el que hace mal--que lo rechaza para escapar de sus convicciones.
Ahora bien, estas dos clases abarcan a toda la humanidad; y por lo tanto,
está claro que este don divino se dispensa a todos.
Los hombres malvados no podrían odiar o rechazar la luz,
si esta no iluminara en algún grado sus mentes,
cuando los reprende a causa de sus malas obras.
No creer,
ni amar la luz--negándose a escuchar y obedecer sus amonestaciones--y
continuar en sus malos caminos satisfaciendo sus propensiones corruptas,
es el motivo de la condenación de estos,
y la causa de su exclusión de esa salvación que es por y a través de Jesucristo.
En cambio, aquellos que caminan por las sendas de la "`verdad`" y la justicia,
en la obediencia de la fe, siguiendo la guía de la luz,
ordenando sus conductas y conversaciones según Sus dictados--todos
los que toman este camino y perseveran en él--son sacados
de las tinieblas y de la muerte de nuestra naturaleza caída,
y hechos partícipes de la salvación de Dios, a través de Jesucristo su Redentor.
(Ver 1 Juan 1:7)

Pero aunque toda la humanidad esté comprendida en estas dos clases,
es una verdad que se desprende claramente de las doctrinas de las Escrituras,
que los individuos pueden pasar de cualquiera de estas clases a la otra.
Aquellos que han comenzado a caminar por las sendas de la verdad y la justicia,
e incluso aquellos que han hecho un considerable avance en la vida religiosa, pueden,
si no permanecen en el temor de Dios y obediencia a Su santa voluntad,
caer en tentación y ser vencidos por ella,
y así convertirse en hacedores de iniquidad (Ezequiel 33:18; 1 Corintios 9:27).^
footnote:[Ver también: Hebreos 6:4-6; 2 Pedro 2:20-21; 1 Corintios 10:12,
1 Corintios 15:1; 2 Corintios 6:1; Romanos 11:20-22; Mateo 13:20-21; Juan 15:2-6;
Apocalipsis 2:5.]
Así también,
si los individuos de la última descripción--antes de que pase el día de
misericordia--abrazan las renovadas visitas de un Dios paciente y misericordioso,
pueden, sin lugar a duda,
(a través del sincero arrepentimiento y fe en Su Hijo Jesucristo) ser limpiados de la
contaminación del pecado y llevados al estado de reconciliación y favor con Dios.
Por tanto, será aplicable a ellos la declaración del apóstol a los corintios,
al describir los varios tipos de malhechores: "`Y esto erais algunos;
mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios`" (1 Corintios 6:11).

Entre otras declaraciones de Cristo en concordancia con lo anterior,
están las siguientes: "`Yo soy la luz del mundo; el que Me sigue, no andará en tinieblas,
sino que tendrá la luz de la vida`" (Juan 8:12). A algunos de los judíos,
que por la incredulidad estaban en peligro de que este don divino les fuera quitado,
les dijo: "`Andad entre tanto que tenéis luz, para que no os sorprendan las tinieblas;
porque el que anda en tinieblas, no sabe a dónde va... Entre tanto que tenéis la luz,
creed en la luz,
para que seáis hijos de luz`" (Juan 12:35-36). Estas declaraciones de Cristo,
en las que Él se representa a Sí mismo bajo la designación de "`la
Luz,`" parecen referirse a Él principalmente como esa Palabra divina,
cuya vida, como declara el apóstol,
es la "`luz de los hombres`" (Juan 1:4). Por la operación de esta Palabra,
se efectúa la obra de regeneración en los que creen y caminan en Su luz.
Ellos son "`renacidos, no de simiente corruptible, sino de incorruptible,
por la palabra de Dios que vive y permanece para siempre`"
(1 Pedro 1:23). Así se convierten en hijos de la luz,
en otras palabras, en verdaderos Cristianos.

Puede observarse además,
que todo el que cree en la luz de Cristo y camina
en obediencia a sus manifestaciones día a día,
participa plenamente de los beneficios procurados
por los sufrimientos y muerte del Redentor.
__"`Si andamos en luz,`"__ dijo el apóstol, "`como Él está en luz,
tenemos comunión unos con otros,
y __la sangre de Jesucristo Su Hijo nos limpia de todo pecado`"__ (1 Juan 1:7). Por tanto,
es evidente que el ser limpiados de todo pecado por medio de la sangre de Cristo,
es el bendito privilegio de aquellos que caminan en la luz.

Cristo es el don de Dios para la humanidad,
no sólo en lo que se refiere a Su aparición externa o personal,
Sus sufrimientos y Su muerte,
sino también en lo que se refiere a Su manifestación espiritual en sus corazones.
El Todopoderoso declara: "`Te di por luz de las naciones,
para que seas mi salvación hasta lo postrero de la tierra`" (Isaías
49:6). Su salvación es gratuitamente ofrecida a todos,
pero sólo participan de ella,
los que en humildad de mente reciben y obedecen esta manifestación de Su luz santa,
o Espíritu, y que al abrazar la fe, que es fruto de esta,
son bautizado en o "`dentro del`"^
footnote:[El Griego no se lee como "`bautizándoles en el
nombre,`" sino "`bautizándoles dentro +++[+++eis+++]+++ del nombre.`"]
nombre--es decir, la vida y poder del Padre,
del Hijo y del Espíritu Santo--como está escrito: "`El que creyere y fuere bautizado,
será salvo`" (Marcos 16:16). La fe de estos abrazará
necesariamente el testimonio de las Sagradas Escrituras,
(si tienen acceso a este invaluable registro) respecto al nacimiento, vida, doctrina,
milagros, muerte, resurrección y ascensión de nuestro Santo Redentor.
Pues la dádiva de la luz, o Espíritu de Cristo,
(especialmente en lo que se refiere a la medida incrementada
que es concedida bajo la dispensación Cristiana) tiene que
ser completamente atribuida a la eficacia de lo que Cristo,
en Su aparición en la carne, hizo y sufrió por la raza humana.
Así, los beneficios de la '`única ofrenda`'^
footnote:[Hebreos 10:14]
no son despreciados,
sino __más completamente exaltados__ por la doctrina de la manifestación del Espíritu,
o luz y gracia universales y salvadoras.

Es evidente que el maligno, mediante varias estrategias,
se esfuerza por inducir a los hijos de los hombres a cerrar
sus corazones contra la influencia de la luz,
o Espíritu de Cristo; y en la medida que tiene éxito en este plan,
en esa misma medida mantiene su poder y dominio malignos en el mundo.
Por ejemplo, si el astuto adversario, con el fin de llevar a cabo su propósito,
engaña a cualquiera de los profesantes del Cristianismo,
al punto de inculcar en su mente una secreta aversión contra
esa manifestación de la luz de Cristo que escudriña el corazón;
y si aprovechando la ventaja que ha ganado de esta manera,
puede inducirlo a etiquetar esta doctrina con el estigma de entusiasmo o fanatismo,
entonces le resultará fácil persuadirlo de que desatienda y rechace
todas las amonestaciones de este maestro divino en su propia mente,
con el fin de llevar a cabo sin restricciones sus propias obras de tinieblas
en su corazón. Pero Aquel que fue manifestado "`para quitar nuestros pecados,`"
también fue manifestado "`para deshacer las obras del diablo.`"
Cuando creemos en esta bendita luz de Cristo y le
permitimos brillar libremente en nuestros corazones,
las obras del adversario son claramente detectadas desde su mismo origen;
y si abrazamos sus advertencias y demandas, por medio del poder que ella imparte,
somos capacitados para "`vencer al maligno`" en sus diversas artimañas,
y para '`renunciar a la impiedad y a los deseos mundanos, y vivir en este siglo sobria,
justa y piadosamente`' (Tito 2:11-12).

La gran importancia de este don divino para la humanidad parece muy evidente
en el relato que hace de él nuestro Señor Jesucristo en los textos ya citados.
Las cartas apostólicas también aportan un testimonio que lo corroboran,
por los términos con los que lo describen y por los efectos que le atribuyen.
En la epístola a los Corintios se declara que "`Dios,
que mandó que de las tinieblas resplandeciese la luz,
__es el que resplandeció en nuestros corazones,__
para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo.
Pero tenemos este tesoro en vasos de barro, para que la excelencia del poder sea de Dios,
y no de nosotros`" (2 Corintios 4:6-7). El mismo
apóstol también describe este don divino como,
"`la gracia de Dios, +++[+++que]
se ha manifestado para salvación a todos los hombres`" (Tito 2:11). También
la presenta como "`el Espíritu de Dios`" o "`de Cristo`" (Romanos 8:9).
Una "`manifestación del Espíritu dada para provecho`" (1 Corintios 12:
7). Es también llamada "`la unción...que enseña todas
las cosas`" (1 Juan 2:27). "`Cristo en vosotros,
la esperanza de gloria`" (Colosenses 1:27). El versículo
5 del capítulo 13 de 2 Corintios es muy enfático:
"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"
"`Todas las cosas que son reprobadas,^
footnote:[Reprobadas, es decir, no aprobadas.]
son hechas manifiestas por la luz`" (Efesios 5:13; RVG).

Además de lo anterior,
los siguientes textos también se presentan haciendo referencia al mismo
don divino usando la frase "`la Palabra,`" o "`la Palabra de Dios.`"
Sin embargo,
hay algunos profesantes Cristianos que estiman que estos textos
deben ser entendidos como una referencia a las Escrituras.
Pero será evidente la incorrección de esta suposición,
si se considera debidamente una porción del contexto de cada cita.
En dicho contexto se encontrará que esta frase abarca atributos,
los cuales según se han concebido, no son atribuibles a las Escrituras,
sino únicamente a Cristo,
quien es "`la Palabra,`" por quien el mundo y todas las cosas en él,
fueron creadas (Hebreos 11:3).

El apóstol Pablo declara que la justicia que es por la fe, habla de esta manera:
"`No digas en tu corazón: ¿Quién subirá al cielo?
(esto es, para traer abajo a Cristo); o, ¿quién descenderá al abismo?
(esto es, para hacer subir a Cristo de entre los muertos).
Mas ¿qué dice?
Cerca de ti está la palabra,
en tu boca y en tu corazón. Esta es la palabra de fe que
predicamos`" (Romanos 10:6-8). El apóstol Santiago exhorta:
"`Recibid con mansedumbre la palabra implantada,
la cual puede salvar vuestras almas`" (Santiago 1:21). El apóstol
Pedro se dirige a los creyentes como aquellos que han "`renacido,
no de simiente corruptible, sino de incorruptible,
por la palabra de Dios que vive y permanece para siempre.
Porque:
Toda carne es como hierba...mas la palabra del Señor permanece
para siempre`" (1 Pedro 1:23-25). En la epístola a los Hebreos
tenemos una descripción muy particular de esta Palabra divina.
El apóstol declara que la "`palabra de Dios es viva y eficaz,
y más penetrante que toda espada de dos filos,
y penetra hasta partir el alma y el espíritu, y las coyunturas y los tuétanos,
y discierne los pensamientos y las intenciones del corazón.
Y no hay cosa creada que no sea manifiesta en su presencia;
antes todas las cosas están desnudas y abiertas a los ojos de Aquél
a quien tenemos que dar cuenta`" (Hebreos 4:12-13). Aquí,
este eminente apóstol le adjudica a la Palabra de Dios,
el divino atributo de la omnisciencia.
Ahora bien,
aquellos que dicen que la "`palabra de Dios`" descrita en este texto es la Escritura,
deben, por supuesto, adjudicarle este atributo (omnisciencia) a ella; pero al hacerlo,
deberán considerar si no se están sujetando a la seria acusación de __idolatrar__ las Escrituras.

El apóstol Pablo nos enseña que las Sagradas Escrituras fueron
dadas por inspiración divina y que son "`útiles para enseñar,
para redargüir, para corregir, para instruir en justicia,
a fin de que el hombre de Dios sea perfecto,
enteramente preparado para toda buena obra`";
y que "`pueden hacer sabio para la salvación por la fe que es en Cristo Jesús`"
(2 Timoteo 3:15-17). Ellas dan testimonio de Cristo como el Salvador del mundo;
exponen la doctrina que Él predicó cuando estuvo personalmente en la tierra,
y describen lo que hizo y sufrió por la humanidad.
También presentan declaraciones muy claras con respecto
a Su aparición espiritual en el alma,
con el fin de efectuar la regeneración y santificación. Pero en
las varias dispensaciones de "`Su gracia y verdad`" a la humanidad,
el Señor Jesucristo "`Sumo Sacerdote de nuestra profesión`" (Hebreos 3:1) obra,
ya sea directamente o por medios externos según Le plazca.
En efecto, una de las excelencias distintivas de la dispensación Cristiana,
es que conduce a la comunión con el Padre y con el Hijo,
la cual no depende de ningún medio externo.
A través de Cristo "`tenemos entrada por un mismo Espíritu al Padre`" (Efesios
2:18). Aunque estimamos mucho el beneficio que se deriva del sagrado registro,
no debemos olvidar que estaríamos abusando de este precioso don,
si lo exaltáramos para colocarlo en el lugar de Aquel que es descrito así:
"`En el principio era la Palabra, y la Palabra era con Dios, y la Palabra era Dios.
Todas las cosas por él fueron hechas.
En él era la vida; y la vida era la Luz de los hombres`" (Juan 1:1, 3,
4 RV1602P). Por tanto,
al atribuirle a la Biblia todo el honor que los mismos escritores inspirados le atribuyen,
tengamos cuidado de no exaltarla por encima,
ni de concederle igualdad con Cristo o con el Espíritu Santo,
de quien se deriva su autoridad.^
footnote:[Sin embargo, es tal la deferencia que se le debe a esta autoridad,
que las Escrituras deben ser consideradas como la única prueba externa adecuada,
por la que se deben decidir las controversias entre los cristianos sobre temas religiosos;
de modo que cualquier doctrina que sea contraria a su testimonio,
puede ser justamente rechazada como falsa.
Además,
todo lo que haga cualquier persona que pretenda tener la
guía del Espíritu y que sea contrario a las Escrituras,
debe ser considerado como efecto de un engaño. Véase la [.book-title]#Apología# de
Robert Barclay, Prop. 3.]

Al publicar esta perspectiva concisa del comienzo
y progreso de la religión viva en el alma,
el escritor desea observar que es probable que caiga en manos de
personas con inclinaciones religiosas de diferentes denominaciones.
Puede que algunas de estas personas estén listas a decir:
"`Esta doctrina no concuerda con lo que estamos acostumbradas
a escuchar de nuestros ministros;
es una doctrina que en muchos puntos fundamentales, hasta donde podemos observar,
rara vez se oye desde un púlpito hoy.`"
En caso de que se levanten objeciones de este tipo en la mente de alguna persona que
con corazón sincero está buscando ese conocimiento que "`es vida eterna`" (Juan 17:3),
el escritor le ruega que considere que esta doctrina fue
abiertamente declarada por nuestro Señor Jesucristo,
y que Sus apóstoles predicaron decididamente las mismas
verdades--abundante prueba de lo cual es hallada al consultar
los varios textos citados en los párrafos anteriores.

Mientras el lector se ocupa en la investigación de este trascendental tema,
también se le ruega encarecidamente recordar su propia experiencia
en momentos pasados de seria reflexión. ¿Acaso no has sido testigo,
al menos en alguna medida, de la verdad de las declaraciones de la Escritura,
a la que ha sido dirigida tu atención en las páginas anteriores?
__¿No ha brillado la luz de Cristo en tu corazón?__ ¿No te ha despertado del estado
de seguridad carnal y colocado tus transgresiones en orden delante de ti,
instándote a romper con tus pecados por medio del arrepentimiento y enmienda de vida?
Tú puedes estar bien seguro de esta verdad,
que no es obra del enemigo de tu alma __detectar y poner al
descubierto__ sus propias artimañas. Él busca más bien engañar,
encubrir y oscurecer sus propios caminos y cebos,
para que no se descubra la verdadera naturaleza y hacia dónde inclinan éstos.
Es la luz de Cristo, nuestro amado Redentor,
la que detecta y da a conocer las obras del gran engañador.

Si ahora estás convencido por el testimonio combinado de
la Luz o Espíritu de Cristo y de las Sagradas Escrituras,
de que la doctrina predicada por los hombres (a quienes
has estimado como ministros del evangelio) no está en completa
concordancia con lo que Jesucristo y Sus apóstoles predicaron,
ciertamente la felicidad eterna se pone en juego en tu fiel abrazo a esto último.
Y si este curso de convicción interna y renovación
de corazón resulta muy opuesto a tu inclinación natural,
como para ser considerado realmente una cruz difícil de soportar; con todo,
recuerda quién es el que dijo: "`Y el que no lleva su cruz y viene en pos de Mí,
no puede ser Mi discípulo`" (Lucas 14:27). Anímate, pues,
__a llevar esta cruz__ y fielmente seguir a Cristo en el camino de la negación al yo.
Uno de los más grandes privilegios que te ofrece la dispensación Cristiana,
es que Él es dado como tu "`Líder,`" tu guía espiritual (Isaías 55:4),
y si en humildad de mente obedeces las instrucciones
de Su santa luz revelada en tu corazón,
__sigues verdaderamente a Cristo.__

Como este es un punto importante de la doctrina Cristiana,
el escritor se inclina a repetir la afirmación,
de que sólo aquel que verdaderamente cree y sigue la luz de Cristo,
es realmente un creyente y seguidor de Cristo, y por lo tanto,
un participante de los beneficios que resultan de Sus sufrimientos y muerte.^
footnote:[Esta afirmación no queda invalidada,
por el hecho de que algunas personas que han profesado (aunque
falsamente) una creencia en la Luz o Espíritu de Cristo,
hayan despreciado y rechazado las Sagradas Escrituras.
Así como el registro sagrado fue escrito bajo la inspiración del Espíritu Santo,
y así como este divino Maestro en sí mismo es inmutable,
evidentemente se deduce que su influencia nunca puede llevar a nadie a
despreciar lo que ha dictado para nuestra instrucción. Por lo tanto,
los que ignoran y rechazan las Sagradas Escrituras demuestran claramente,
independientemente de lo que profesen, que sus mentes,
en lugar de estar bajo la influencia de la Luz o el Espíritu de Cristo,
están envueltas en graves tinieblas y engaños.]
Por el contrario, el que en la práctica desprecia y rechaza esta Luz,
desprecia y rechaza a Cristo,
y así se priva de esa salvación de la que los que creen y siguen a Cristo participan.
Estas posiciones son apoyadas por los textos citados al principio de este capítulo,
tomados en relación con Juan 8:12 y 1 Juan 1:7. Un testimonio que corrobora esto aparece
también en la siguiente declaración de gracia del Todopoderoso con respecto a Cristo,
ya citado: __"`Te di por luz de las naciones,
para que seas mi salvación hasta lo postrero de la tierra`"__ (Isaías 49:6). Los que creen
y siguen esta Luz divina son favorecidos con la entrada a la fuente de sabiduría y fortaleza.
A través de la fe reciben poder para cumplir sus demandas;
y el obediente es recompensado con paz y gozo.
"`¡Gracias a Dios por su don inefable!`" (2 Corintios 9:15)

Que la atención de los sinceros buscadores de la verdad
se vuelva día a día hacia este monitor interior,
el verdadero guía espiritual.
Éste no los llevará, de ninguna manera, a despreciar las Sagradas Escrituras.
Por el contrario,
los hará capaces de entenderlas más verdaderamente en el sentido en que fueron escritas,
que lo que pueden lograr las mejores facultades del hombre sin ayuda;
y aplicarlas más efectivamente para su propia instrucción y consuelo.
Además, la armonía de la que serán testigos según avanzan en el progreso religioso,
entre la ley del Espíritu escrita en el corazón y
los preceptos y doctrinas contenidos en la Biblia,
(en la medida que este último se aplique a sus estados individuales)
no dejará de proporcionarles mucha satisfacción y ánimo.
Entonces,
para evitar que caigan en alguna tentación mediante la cual el
enemigo se esfuerce por estropear la obra del Señor en sus almas,
dejen que sus anhelos secretos (bajo la influencia del Espíritu
de Cristo) asciendan frecuentemente al Padre celestial,
con fervientes deseos de que venga Su reino y se establezca en sus corazones,
y que sea hecha Su santa voluntad en y por ustedes, en todas las cosas.
Y cuando la Luz de Cristo señale lo que requiere de ustedes como individuos,
tanto para hacer lo que es correcto ante Sus ojos, y evitar lo que es malo,
que el lenguaje de cada alma sea: "`No se haga mi voluntad, Señor, sino la tuya.`"
Al esforzarse así por seguir a su Redentor en todas las cosas,
mediante esa ayuda divina que ciertamente le será otorgada
a todo aquel que busca con sinceridad de corazón,
encontrará que Su misericordiosa declaración, ya citada, se cumple en su experiencia:
"`Yo soy la luz del mundo; el que Me sigue, no andará en tinieblas,
sino que tendrá la luz de la vida.`"

El apóstol Pablo hizo esta observación con respecto a los judíos:
"`Cada vez que se lee a Moisés,`" (quien escribió de Cristo, Juan 1:45),
"`un velo está puesto sobre sus corazones; pero cuando alguno se vuelve al Señor,
el velo es quitado`" (2 Corintios 3:15-16 LBLA).
Eso mismo puede decirse hoy de muchos Cristianos profesantes,
que cuando leen el Nuevo Testamento, el velo está sobre sus corazones en alguna medida.
Porque aunque reciben la doctrina contenida en las Escrituras
con respecto a la aparición externa o personal de Cristo,
Sus sufrimientos y muerte por la humanidad--doctrina que la fe Cristiana
abraza plenamente--todavía son deficientes con respecto a ese importante
artículo de la misma fe que el apóstol refuerza con este enfático lenguaje:
"`Examinaos a vosotros mismos si estáis en la fe; probaos a vosotros mismos.
¿O no os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"
(2 Corintios 13:5) Él también declara que "`si alguno no tiene el Espíritu de Cristo,
no es de él`" (Romanos 8:9).

No obstante,
nosotros podemos tener la misma seguridad con respecto
a los Cristianos profesantes recién mencionados,
que la que expresó el apóstol con respecto a los judíos; es decir,
que cuando sus corazones '`se vuelvan al Señor,
el velo se quitará.`' Cuando este cambio tome lugar, (¡Oh,
que se efectúe rápidamente!) entonces estarán preparados para recibir la Luz,
o Espíritu de Cristo como "`Líder`" (Isaías 55:4). Y al
someterse al bautismo de Cristo que purifica el corazón,
y seguirlo en el camino de regeneración y santificación,
producirán el fruto del Espíritu a través de Su influencia vivificante.
El apóstol declara que este fruto es: "`Amor, gozo, paz, paciencia, benignidad, bondad,
fe, mansedumbre, templanza`" (Gálatas 5:22-23). Otra vez:
"`El fruto del Espíritu es en toda bondad, justicia y verdad`" (Efesios 5:9).

¿Qué mayor bendición puede desear el benefactor más ilustrado para toda la raza humana
que ésta--que el fruto del Espíritu arriba descrito sea universalmente producido?
Entonces el mal moral sería expulsado de la faz de la tierra;
y "`Los reinos del mundo +++[+++vendrían]
a ser de nuestro Señor y de su Cristo; +++[+++quien]
reinará por los siglos de los siglos`" (Apocalipsis 11:15).
