[#adoracion, short="La Adoración Ordenada por Dios"]
== Capítulo II. La Adoración Ordenada por Dios Bajo la Dispensación Cristiana

En la conversación que nuestro Señor accedió sostener con la mujer de Samaria, declaró:

[quote.scripture, , Juan 4:23-24]
____
"`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en espíritu y en verdad;
porque también el Padre tales adoradores busca que le adoren.
Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que adoren.`"
____

En otra ocasión Él dijo: "`Nadie viene al Padre, sino por Mí`" (Juan 14:6). Y:
"`Separados de Mí nada podéis hacer`" (Juan 15:5). Estas declaraciones claramente indican
que la adoración a Dios bajo la dispensación Cristiana es de carácter espiritual,
y debe ser ofrecida en verdad;
y que no podemos ir al Padre (y ofrecerle a Él esta verdadera adoración) sino por Jesucristo,
quien es __"`el camino, y la verdad, y la vida.`"__
Por tanto,
Su asistencia es comunicada a nosotros por medio
de la influencia vivificadora de Su Espíritu Santo,
sin la cual el importante deber de la adoración no puede ser aceptablemente realizado.
Este parece haber sido el sentimiento del apóstol Pablo,
porque él declara que "`nadie puede llamar a Jesús Señor, sino por el Espíritu Santo.`"
Por lo tanto, queda claro,
que toda adoración que tenga un origen diferente no es la verdadera adoración a Dios,
sino más bien, la que el apóstol denomina como "`adoración voluntaria`"^
footnote:[Nota del editor:
Aquí Rundell está citando la traducción de la RVG de Colosenses 2:23 que,
aunque es una traducción muy precisa de la palabra griega subyacente,
es una frase poco familiar para la mayoría de los cristianos modernos.
Las versiones más contemporáneas suelen traducir la misma palabra (también con
precisión) como "`adoración autoimpuesta`" o "`religión hecha por uno mismo`".]
(Colosenses 2:23, RVG).
Es denominada así porque es un acto meramente del yo;
el mero producto de la voluntad y de la sabiduría del hombre,
esté o no adornada con elocuencia de palabra,
o acompañada con música vocal o instrumental.
Incluso,
si esta adoración estuviera apoyada por la autoridad humana y aprobada como ortodoxa,
la declaración de Jesucristo sigue siendo aplicable a ella: "`Pues en vano me honran,
enseñando como doctrinas, mandamientos de hombres`" (Mateo 15:9).

Puede decirse de los Cristianos meramente nominales de hoy,
que aunque en muchos casos la falta de reflexión respecto
a la religión es el rasgo predominante de sus caracteres,
aun así en muchos otros casos,
son celosos al apoyar los credos de las
comunidades religiosas a las que están individualmente vinculados.
Pero a pesar de su celo, se niegan a someterse a las convicciones del Espíritu de Cristo,
no quieren acudir a Su bautismo, se niegan a caminar por el camino de la negación al yo;
y la consecuencia es que sus corazones no son limpiados, la paja no es quemada,
y siguen teniendo una mentalidad carnal.
Ahora bien,
mientras continúen en este estado de resistencia contra el Espíritu de Cristo,
hay motivos para que teman que la adoración que ellos le ofrecen al Todopoderoso Dios,
no sea más aceptable ante Sus ojos que la de los fariseos en el pasado.
Los fariseos rechazaron a Cristo en Su aparición externa o personal;
los Cristianos meramente nominales arriba descritos,
rechazan a Cristo en Su aparición interna o espiritual en sus corazones.
Como los fariseos, piensan que "`tienen vida eterna`" en las Escrituras;
y como ellos también, no quieren acudir a Cristo para "`tener vida.`"
(Ver Juan 5:39-40)

Pero es muy lamentable que el adversario de la humanidad domine tanto,
no sólo desviando al Cristiano meramente nominal
de entrar siquiera en el verdadero viaje espiritual,
sino también impidiendo el progreso de muchas personas
serias que han comenzado a caminar en él;
es decir, el progreso de aquellas que,
amando al Señor Jesús en un buen grado de sinceridad,
han seguido Su guía santa al punto de ser redimidas
de muchas malas costumbres y vanidades del mundo.
No obstante, al no someterse paciente y humildemente a la operación de ese poder,
por el que '`las cosas viejas pasan y todas son hechas nuevas,
y todo esto proviene de Dios`' (2 Corintios 5:17-18),
ven obstruido su crecimiento en la vida divina.
Su fuerte apego a las prescripciones humanas (con respecto
a las formas de adoración y prácticas ceremoniales),
les impide alcanzar esa claridad de discernimiento
espiritual en la que habrían sido introducidos,
si en la simplicidad de un niño, hubieran permanecido pasivos en la mano del Señor,
como la arcilla en la mano del alfarero.
En este estado de sumisión defectuoso a la divina voluntad,
no están en la capacidad de apreciar debidamente los beneficios
que resultan de una fe práctica __en el nombre__ (es decir,
en el poder, vida, luz, etc.) del Hijo de Dios.
Sus perspectivas y dependencia (al estar dirigidas al exterior)
se limitan a una mera explicación literal de este nombre santo;
no pueden, por tanto,
percibir claramente la necesidad de buscar y esperar la influencia divina
para efectuar la necesaria preparación de corazón delante de Él,
antes de ofrecer sus oraciones en el trono de la gracia.
Y si en sus asambleas para la adoración divina no se reúnen en el nombre de Cristo,
¿puede esperarse que Él esté en medio de ellos?
(Ver Mateo 18:20)

La necesidad de la influencia del Espíritu de Cristo en este solemne acto de adoración,
es plenamente reconocido por el apóstol Pablo.
Pues, a pesar de sus extraordinarios dones y larga experiencia en el ministerio del Evangelio,
declara con respecto a sí mismo y a sus compañeros creyentes:
"`Y de igual manera el Espíritu nos ayuda en nuestra debilidad;
pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros con
gemidos indecibles,`" (Romanos 8:26) es decir,
como observa una escritora^
footnote:[Priscilla H. Gurney (1757-1828)]
recientemente muerta: "`Con fervientes deseos internos,
el perceptible efecto de esa poderosa causa; o sea,
la silenciosa operación del Espíritu de verdad,
mostrándole al hombre de tiempo en tiempo su verdadera condición,
y enseñándole directamente tanto por qué orar y cómo orar correctamente.`"

Adoremos y sirvamos a Dios por medio de Él, Jesucristo, "`en novedad de espíritu,
y no en lo antiguo de la letra`" (Romanos 7:6, RVG), creyendo __en Su nombre;__ es decir,
en ese nombre que Dios ha exaltado sobre todo nombre,
"`para que en el nombre de Jesús se doble toda rodilla de los que están en los cielos,
y en la tierra, y debajo de la tierra; y toda lengua confiese que Jesucristo es el Señor,
para gloria de Dios Padre`" (Filipenses 2:10-11). Si la verdadera __inclinación
ante el nombre de Jesús__ fuera entendida y experimentada en nuestros corazones;
si fuéramos tan humillados por Su poder como para someternos a Su gobierno,
por muy contraria que fuera a nuestras opiniones y prácticas anteriores;
si la realización de nuestros deberes religiosos y morales
fueran llevados a cabo bajo Su santa influencia y control,
entonces seríamos realmente Cristianos.
Seríamos capaces de dirigirnos a Jesucristo en verdad como nuestro __Señor;__
al ser Su santa luz nuestro Líder,
y Su santa voluntad (dada a conocer a nosotros por
dicha luz) hecha en y por nosotros en todas las cosas.
Así sería el nombre de Jesús "`exaltado sobre todo`" otro "`nombre,
para gloria de Dios el Padre.`"

Al inicio de este capítulo se hizo referencia a aquellos Cristianos meramente nominales,
quienes al rechazar las amonestaciones de la luz de Cristo,
se niegan a entrar en el camino de la negación al yo, y en consecuencia,
son descalificados (mientras persistan en su desobediencia) de
la realización de esa adoración que es en espíritu y en verdad.
Mi propósito al desarrollar este tema,
es mostrar la necesidad no sólo de entrar "`por la puerta estrecha,`"
sino también de __continuar__ "`caminando en el camino estrecho,`"
llevando la cruz diariamente y siguiendo a Cristo;
para que el Cristiano viajero pueda ser preservado de descansar en sus propias obras,
confiando en una apariencia de piedad sin vida y poder.
Ojalá la consciencia de este peligro impresione profundamente
la mente de las personas religiosamente dispuestas,
a las que nos hemos dirigido en los varios párrafos anteriores de este capítulo.
Con el fin de poner este tema delante de ellas desde un punto de vista más claro,
se les solicita que presten seria atención a las siguientes observaciones
cimentadas principalmente en el siguiente precepto de nuestro Redentor,
a quien (recordémoslo siempre) nuestro Padre celestial nos ha ordenado
oír (Mateo 17:5). __"`Si alguno quiere venir en pos de mí,`"__ en otras palabras,
si alguno quiere ser verdaderamente Cristiano, __"`niéguese a sí mismo,
tome su cruz cada día, y sígame`"__ (Lucas 9:23).

Los efectos que resultan de perseverar fielmente en este camino (el cual,
debemos reconocer, nuestro propio Salvador nos ha señalado),
son brevemente descritos por el apóstol Pablo de la siguiente manera:
"`Con Cristo estoy juntamente crucificado; mas vivo, ya no yo,
sino que Cristo vive en mí; y lo que ahora vivo en la carne,
lo vivo en la fe del Hijo de Dios,
el cual me amó y se entregó a sí mismo por mí`" (Gálatas 2:20 RVG).
Este notable ministro de Cristo no sólo experimentó
el '`hacer morir`' la carne en su propia persona,
sino que también lo requería de aquellos entre quienes
obraba con el siguiente enfático lenguaje:
"`Digo, pues: Andad en el Espíritu; y no satisfagáis la concupiscencia de la carne.
Porque la carne codicia,`" o lucha, "`contra el Espíritu, y el Espíritu contra la carne;
y éstos se oponen entre sí,
para que no podáis hacer lo que quisiereis`" (Gálatas 5:16-17 RVG).
Y con el fin de convencernos de que caminar en el Espíritu y llevar la cruz diariamente
es absolutamente necesario para llegar a ser verdaderos Cristianos,
declara:
"`Pero los que son de Cristo han crucificado la carne con
sus pasiones y concupiscencias`" (Gálatas 5:24 RVG).

Esta observación del apóstol con respecto al conflicto
que toma lugar entre el Espíritu y la carne,
puede considerarse aplicable a toda la humanidad,
por muy diversa que sea la profesión religiosa.
Ahora bien, al que nos unamos y obedezcamos (ya sea al Espíritu o a la carne),
por ese somos influenciados y gobernados: "`Sois esclavos de aquel a quien obedecéis;
ya sea del pecado para muerte,
o de la obediencia para justicia`" (Romanos 6:16).
El Espíritu nos impulsa a negarnos a nosotros mismos,
a crucificar la carne tomando la cruz diariamente, y a seguir a Cristo;
sus purificantes efectos en nuestros corazones son demostrados por nuestro vivir "`sobria,
justa y piadosamente,
en este presente mundo`" (Tito 2:11). Y si este instructor divino es obedecido en sus
posteriores manifestaciones en nuestros corazones (a través de la habilidad que imparte),
nos capacitará para "`adorar al Padre en Espíritu y en verdad.`"

Pero el tentador,
lucha a través de la carne de varias maneras para
obstruir y evitar estos muy deseables resultados.
Cuando sus esfuerzos son ineficaces para hacer que las mentes despiertas
vuelvan a sus antiguos hábitos de abierta irreligión y pecado,
entonces emplea una trampa más siniestra,
al asumir un carácter religioso y hacer una demostración superficial
de piedad y devoción mientras sigue oponiéndose al Espíritu Santo.
Esta oposición al Espíritu se lleva a cabo por medio de insinuaciones engañosas,
calculadas para evitar que las vivificantes advertencias
del Espíritu sean escuchadas y obedecidas.

En particular,
el enemigo se esfuerza por avivar y fomentar en las mentes de muchos profesantes Cristianos,
una aversión al deber de "`velar,`" (Efesios 6:18; Marcos 13:37; Mateo 14:38;
Colosenses 4:2),
lo cual parece incluir la paciente espera en el Señor en el ejercicio de la fe y el amor.
(Ver Oseas 12:6; Isaías 40:31;
Salmo 40:1) Este deber está misericordiosamente diseñado
para que sea el medio por el cual en la quietud^
footnote:["`Estad quietos, y conoced que yo soy Dios`" (Salmo 46:10)]
(todos nosotros siendo débiles y endebles y susceptibles de ser engañados)
el corazón sincero pueda oír la voz del "`buen Pastor,`" y recibir de
Él la instrucción para percibir y la fuerza para evitar la tentación,
así como también la habilidad para ofrecer sus oraciones
en Su santo nombre a su Padre celestial.

Pero el enemigo, a través de la mente carnal,
sugiere dudas sobre si este deber de velar es realmente obligatorio.
Con el fin de desviar eficazmente a los profesantes
de la religión de la práctica de ello,
los impulsa a colocar la confianza __en su propia sabiduría y actividad,__
en lugar de someterse a un ejercicio mental que exija tal negación al yo.
En todos los casos en que estas insinuaciones son abrazadas y seguidas,
las secretas advertencias del Espíritu de Cristo son gradualmente desatendidas;
entonces sobrevienen las tinieblas y la gran obra de purificación del corazón es obstruida.
Ellos buscan, y pronto encuentran,
un camino que es más agradable para la voluntad natural
y para el orgullo del corazón del hombre,
que aquel que requiere la negación al yo y llevar pacientemente la cruz diaria.
Como la fe de ellos no está fundada en el poder de Dios
sino en la sabiduría de los hombres (1 Corintios 2:5),
frecuentemente corren en pos de uno u otro ministro elocuente,
sin considerar la declaración de Cristo: "`El reino de Dios está dentro de vosotros`";
ni buscan la manifestación de este reino y la justicia de Dios
según Su mandato (Mateo 6:33). Conforme avanzan en este camino,
se van apegando fuertemente (en muchos casos) a las formas y ceremonias
establecidas y ordenadas por la sabiduría y autoridad humana;
y así son introducidos en la práctica de la "`adoración voluntaria.`"^
footnote:[Colosenses 2:23 RVG, o "`religión humana`" LBLA]

Desgraciadamente,
¡cuán oscurecido está el brillo del genuino Cristianismo en el presente,
entre sus muchos profesantes,
por no vigilar y evitar debidamente la influencia y los esfuerzos de la mente
carnal en cada forma bajo la cual se opone y lucha contra el Espíritu de Cristo.
Ellos probablemente admitan que es necesario velar para evitar la violación
de los preceptos de moralidad en sus conductas y conversaciones en general,
pero parecen no estar suficientemente conscientes de que es especialmente necesaria
en lo que se refiere a la adoración que ofrecen al Todopoderoso Dios.
Porque en la medida que se dejan llevar por la actividad
del yo o de la carne en este solemne encargo,
sus mentes quedan imposibilitadas de recibir la vivificante
influencia del Espíritu de Cristo,
el único a través del cual se puede ofrecer la adoración
aceptable que es en Espíritu y en verdad.
De modo que, por muy ardiente que sea su celo en los ejercicios devocionales,
y por muy agradables que sean las pasiones que despierta, aun así,
si la influencia por la que actúan en su adoración no es la del Espíritu de Cristo,
la conclusión inevitable es que procede del yo o de la mente carnal.

Cuán necesario es, entonces,
que los profesantes Cristianos de todas las denominaciones (bajo la convicción del gran
peligro que significaría para ellos un error en este importante asunto) abran sus corazones
con toda humildad y sinceridad al penetrante rayo de la luz de Cristo,
la norma a la que el apóstol dirige nuestra atención--"`Pero
todas las cosas que son reprobadas,
son hechas manifiestas por la luz, porque lo que manifiesta todo, es la luz`";
Efesios 5:13--para que bajo su dirección,
puedan formarse un juicio verdadero sobre cuál influencia
ha obtenido el gobierno en sus mentes.

Las tristes consecuencias de seguir actuando bajo la influencia
de eso que se opone al Espíritu de Cristo,
pueden inferirse de estas palabras del mismo apóstol: "`Porque la mente carnal es muerte,
pero la mente espiritual, vida y paz: Porque la mente carnal es enemistad contra Dios;
porque no se sujeta a la ley de Dios, ni tampoco puede.
Así que, los que están en la carne,`" (aquellos en los que la mente carnal predomina),
"`no pueden agradar a Dios`" (Romanos 8:6-8, RVG).
A lo que puede añadirse, que por muy alto que puedan calificar sus logros religiosos,
mientras permanezcan en este estado,
son incapaces de participar en esa comunión que "`es con el Padre,
y con su Hijo Jesucristo`" (1 Juan 1:3).

Volviendo a la descripción que el apóstol da de su propia experiencia ya citada,
tengamos en cuenta lo que dice en otro lugar, de este mismo e importante tema:

[quote.scripture, , Rom 6:3-6]
____
"`¿O no sabéis que todos los que hemos sido bautizados en Cristo Jesús,
hemos sido bautizados en su muerte?
Porque somos sepultados juntamente con él para muerte por el bautismo,
a fin de que como Cristo resucitó de los muertos por la gloria del Padre,
así también nosotros andemos en vida nueva...sabiendo esto,
que nuestro viejo hombre fue crucificado juntamente con él,
para que el cuerpo del pecado sea destruido, a fin de que no sirvamos más al pecado.`"
____

[.no-indent]
Al conformarse así a la doctrina de su Señor de llevar la cruz cada día,
y al someterse al bautismo del Espíritu Santo, el apóstol fue capaz de decir:
"`Con Cristo estoy juntamente crucificado, y ya no vivo yo,
mas vive Cristo en mí`" (Gálatas 2:20).

Ojalá todos los profesantes del Cristianismo sean estimulados
y animados a seguir adelante para alcanzar este estado^
footnote:[Que no se suponga que los altos privilegios que la dispensación
Cristiana ofrece a la humanidad no incluyen el logro de este estado.
Nuestro Señor Jesucristo oró al Padre no sólo en nombre de Sus seguidores inmediatos,
sino también por aquellos que creerían en Él a través de su palabra:
"`Para que todos sean uno; como tú, oh Padre, en mí, y yo en ti,
que también ellos sean uno en nosotros&hellip; __Yo en ellos, y Tú en Mí,__`" etc.;
concluyendo Su súplica (que debe leerse con reverencia y temor) con estas palabras:
"`Y yo les he dado a conocer tu nombre, y lo daré a conocer aún;
para que el amor con que me has amado, esté en ellos, y yo en ellos.`"
(Juan 17:20,21,23,26)], según la medida de luz divina o gracia que se les dispense.
Ojalá sean humillados de tal manera por el poder de Dios,
que estén dispuestos a "`negar al yo,`" "`la carne`" o "`la mente carnal`";
en otras palabras,
'`a despojarse del viejo hombre con sus hechos`'
(Colosenses 3:9),
no sólo de sus prácticas manifiestamente corruptas y pecaminosas,
sino también de sus actos de devoción--sus oraciones y cantos,
y (con respecto al ministerio) sus predicaciones también. Entonces,
al seguir a Cristo en la regeneración (Mateo 19:28),
serán capacitados para '`vestirse del nuevo hombre,
que fue creado según Dios en justicia y en santidad verdadera`' (Efesios 4:24). Y llegarán
a ser verdaderos adoradores--como los creyentes de antaño--__'`adorando a Dios en espíritu,
regocijándose en Cristo Jesús, y no teniendo confianza en la carne`'__ (Filipenses 3:3).

Las Escrituras declaran que "`todos los que son guiados por el Espíritu de Dios,
los tales son hijos de Dios,`" (Romanos 8:14) y que "`a cada uno le es dada la
manifestación del Espíritu para provecho`" (1 Corintios 12:7). Cuán deseable,
cuán indispensable entonces es,
que todos--y especialmente aquellos que se llaman a sí mismos ministros de Cristo--sigan
la manifestación y guía de Su Espíritu en sus propias mentes.
La enseñanza del Espíritu de Cristo siempre está en concordancia con Sus
doctrinas y preceptos que nos son presentados en las Escrituras.
Por lo tanto,
aquellos que están en el oficio como ministros de Cristo (si son verdaderamente tales,
y son efectivamente guiados por Su Espíritu) manifestarán,
no sólo en sus conductas y conversaciones, sino también __en sus ministerios,__
una fiel adhesión a esa porción de Su doctrina a la que ya nos hemos referido,
en la que Él insiste en la necesidad de negar al yo, tomar la cruz cada día y seguirlo.

Pero si alguno de los que emprenden el oficio del ministerio Cristiano,
muestra en su conducta general una disposición a evadir la negación al yo,
a rehuir llevar la cruz y a '`despojarse del viejo
hombre con sus hechos`' (Colosenses 3:9);
si en lugar de seguir al Espíritu de Cristo en su ministerio,
sigue las sugerencias de su propia "`sabiduría carnal`" (2 Corintios 1:12),
"`enseñando como doctrinas,
mandamientos de hombres,`" (Mateo 15:9) la declaración misma de nuestro
Señor parece autorizar la conclusión de que su adoración es "`en vano.`"
Y cuando alguno de los que declinan el uso de los modos
y formas de adoración prescrita por la autoridad humana,
y profesan depender de la dirección del Espíritu de Verdad,
no espera en humildad de mente Su influencia vivificante,
sino que en su propia voluntad y bajo el impulso del celo de la
criatura empieza a predicar o a orar en su asamblea pública,
estas actuaciones,
como la ofrenda de fuego extraño bajo la dispensación mosaica (Levítico 10:1),
pueden ser consideradas particularmente ofensivas a la vista divina.

En todos estos casos, a menos que ellos se sometan a esa palabra divina,
de la que se dice que es "`como martillo que quebranta la piedra`" (Jeremías 23:29);
y a menos que por su efectiva operación sean llevados a
la experiencia de la verdadera humillación y contrición,
y a través del arrepentimiento,
experimenten la purificación del corazón del orgullo y exaltación del yo,
corren el peligro de llegar a ser como algunos antiguos de los que leemos,
que '`cierran el reino de los cielos delante de los hombres,`' que ni entran ellos mismos,
ni dejan '`entrar a los que están entrando`' (Mateo 23:13). Si persisten en este camino,
desatendiendo las convicciones del Espíritu de Cristo, el cual,
desde el momento en que empezaron a rechazar Sus advertencias en sus propias consciencias,
puede presumirse que no ha dejado de reprenderlos de tiempo en tiempo,
estarán más y más "`cargados de maldad`" (Isaías 1:4). Y por este
continuo transgredir la ley escrita en la tabla del corazón,
tendrán muchos motivos para temer--por muy exitoso que estimen sus labores ministeriales--que
finalmente su porción será con aquellos de los que nuestro santo Redentor ha declarado:
"`Muchos me dirán en aquel día: Señor, Señor, ¿no profetizamos +++[+++o predicamos]
en tu nombre, y en tu nombre echamos fuera demonios,
y en tu nombre hicimos muchos milagros?
Y entonces les declararé: Nunca os conocí; apartaos de mí,
hacedores de maldad`" (Mateo 7:22-23).
