== Capítulo III. Bautismo, Adoración y Participación de la Carne y Sangre

Los requisitos solicitados para la admisión en la iglesia
de Cristo no incluyen la ejecución de ninguno de los tipos,
ceremonias y ordenanzas carnales de la dispensación mosaica, o esa de Juan el Bautista,
todo lo cual fue cumplido y abrogado por el Hijo
de Dios en Su aparición personal y muerte en la cruz.
Pero el apóstol Pablo claramente declara, que "`si alguno no tiene el Espíritu de Cristo,
el tal no es de Él`" (Romanos 8:9); es decir,
si algún hombre no ha aceptado al Espíritu de Cristo como su Maestro,
su Bautizador y su Santificador, sino que por el contrario,
con respecto a estos oficios Lo ha despreciado y rechazado, este hombre no es de Cristo.
No importa cuál sea su profesión o su actuación en cuanto a la religión,
o si es miembro de la "`Iglesia Establecida,`" o disidente de ella,
el tal no es miembro del cuerpo espiritual o iglesia de la que Cristo es la cabeza.
Pues según la doctrina del mismo apóstol,
el bautismo por medio del cual los creyentes son introducidos en esta iglesia,
es el bautismo del Espíritu, (1 Corintios 12:13); en consecuencia,
no es ese con agua aplicado ya sea por aspersión o inmersión.
El bautismo del Espíritu es una obra interna;
y no debe olvidarse que no es el cuerpo, sino el alma del hombre,
la que es el objetivo de él.

Juan el Bautista hace una muy clara distinción entre
su bautismo con agua y el bautismo de Cristo:
"`Yo a la verdad os bautizo en agua para arrepentimiento; mas el que viene tras mí,
es más poderoso que yo; cuyo calzado no soy digno de llevar;
Él os bautizará con el Espíritu Santo,
y con fuego`" (Mateo 3:11). Y una declaración similar e igualmente clara de los
dos bautismos es dada por nuestro Señor (Hechos 1:5). Este bautismo con el Espíritu
Santo es al que ya se ha hecho referencia en el primer capítulo de este libro.
Es la obra del Espíritu de Cristo operando en el alma del hombre,
principalmente de manera directa,
pero algunas veces también de manera indirecta a través de los ministros del Evangelio.
Este ministerio bautismal parece haber sido instituido por Jesucristo mismo,
aunque no encontramos que les haya dado alguna comisión
a Sus discípulos de bautizar con agua,
o que Él mismo haya bautizado a alguien así. Leemos
que después de Su resurrección les declaró:
"`Toda potestad me es dada en el cielo y en la tierra,`" añadiendo, "`id,
y enseñad a todas las naciones,
bautizándoles en el nombre (el poder y la vida divina) del Padre, y del Hijo,
y del Espíritu Santo.
(Mateo 28:18-19).

De este ministerio bautismal,
tenemos un ejemplo en el relato que da el apóstol
Pedro de su visita a la familia de Cornelio.
"`Y cuando comencé a hablar, cayó el Espíritu Santo sobre ellos también,
como sobre nosotros al principio.
Entonces me acordé de lo dicho por el Señor, cuando dijo:
Juan ciertamente bautizó en agua, mas vosotros seréis bautizados con el Espíritu Santo.`"
Y luego el apóstol añade: "`Dios, pues,
les concedió también el mismo don`" (Hechos 11:15-17).

Así, pues, el don del Espíritu Santo parece haber acompañado la predicación de Pedro,
y fue comunicado independientemente del bautismo en agua.
No obstante,
este apóstol no estaba entonces totalmente destetado del apego a esta ordenanza figurativa;
porque parece que en este primer caso de conversión gentil,
ordenó que se les administrara a los que previamente
habían recibido al Espíritu Santo (Hechos 10:47-48),
aunque con alguna duda, que la pregunta: "`¿Puede acaso alguno impedir el agua?`"
parece implicar.
Con el paso del tiempo, sin embargo,
las opiniones sobre el bautismo de este eminente apóstol parecen haberse ampliado;
porque encontramos en su epístola universal,
al describir el bautismo por el que los creyentes son salvos ahora,
declara que '`no es la eliminación de las inmundicias
de la carne,`' (que es el efecto propio del bautismo,
o lavamiento, en agua) '`sino el testimonio de una buena conciencia delante de Dios,
por la resurrección de Jesucristo`' (1 Pedro 3:21). Ahora,
esta es una descripción del efecto del bautismo de Cristo con el Espíritu
Santo y con fuego--mediante el cual se experimenta una muerte al pecado
y un nuevo nacimiento a la justicia (a través de la fe en ese poder divino
por el que Cristo se levantó de entre los muertos).
Y así se produce la respuesta o testimonio de una buena consciencia.

El lenguaje del apóstol Pablo de este tema es también muy instructivo.
Después de hacer referencia al misterio que había estado escondido por siglos y generaciones,
pero que entonces había sido manifestado a los santos,
el cual (dice que) "`es Cristo en vosotros, la esperanza de gloria.
A quien nosotros predicamos, amonestando a todo hombre,
y enseñando a todo hombre en toda sabiduría,
a fin de presentar perfecto en Cristo Jesús a todo hombre.`"
Luego prosigue: "`Por tanto, de la manera que habéis recibido al Señor Jesucristo,
andad en Él`"; y "`vosotros estáis completos en Él,
el cual es la cabeza de todo principado y potestad`";
y "`sepultados con Él en el bautismo, en el cual también sois resucitados con Él,
mediante la fe en el poder de Dios que le levantó de los muertos`" (Colosenses 1:26-28;
2:6,10,12). "`Porque somos sepultados con Él en la muerte por el bautismo;
para que como Cristo resucitó de los muertos por la gloria del Padre,
así también nosotros andemos en novedad de vida`" (Romanos
6:4). Este es ese único bautismo del que habla el apóstol:
"`Un cuerpo, y un Espíritu...un Señor, una fe, un bautismo.`"
(Efesios 4:4-5) Y describiendo el agente de esta importante obra
(ya sea que haya comenzado a través de la predicación externa,
o no) declara:
"`Porque por un solo Espíritu somos todos bautizados en un cuerpo,`" o Iglesia de Cristo,
"`y todos hemos bebido de un mismo Espíritu`" (1 Corintios 12:13).

Los términos "`agua`" y "`fuego`" se usan en el Nuevo Testamento en referencia
al bautismo de Cristo y al nuevo nacimiento que es efecto de dicho bautismo.
Se dice de Cristo: "`Él os bautizará con el Espíritu Santo,
y con fuego`" (Mateo 3:11). Leemos de nuevo:
"`...el que no naciere de agua y del Espíritu,
no puede entrar en el reino de Dios`" (Juan 3:5). Pero estos
términos en los textos citados no deben ser entendidos literalmente,
sino figurativamente.
Así como es propiedad del agua limpiar y del fuego refinar,
así limpia y refina el bautismo de Cristo al alma sometida a éste,
de las manchas y escoria del pecado.

Durante la época apostólica,
cuando el bautismo de Cristo era administrado a través de la predicación del Evangelio,
en muchos casos iba acompañado de dones milagrosos.
Sin embargo, no tenemos motivos para concluir ahora, ante la ausencia de tales dones,
que una medida de la misma influencia bautismal del Espíritu,
no siga acompañando el ministerio de aquellos que Él llama,
capacita y emplea en Su servicio,
y que actúan sólo bajo Su ministración y guía en humilde dependencia de Su sabiduría,
vida y poder.
A través de la bondadosa continuidad de la misericordia y amor divinos,
esta influencia es todavía experimentada en mayor o menor grado cuando la palabra,
así predicada, es "`mezclada con fe`" en aquellos que la oyen (Hebreos 4:2).

Algunos de los defensores del bautismo con agua ponen mucho énfasis
en los ejemplos que están registrados en el Nuevo Testamento,
en los que algunos de los apóstoles parecen haber usado esta ordenanza tipológica,
o haber dirigido a ella.
Pero cuando se considera que algunos de los apóstoles,
durante un tiempo después de la crucifixión y ascensión de nuestro santo Redentor,
practicaron no sólo el bautismo en agua, sino también otras ordenanzas tipológicas^
footnote:[Como, por ejemplo, las fiestas,
los votos y los ritos de purificación del templo (Hechos 18:21; 21:21-24),
las creencias relacionadas con los alimentos limpios e impuros (Hechos 10:10-15),
sangre y animales estrangulados (Hechos 15:20, 29),
la necesidad de separarse de los gentiles (Hechos 10:28; Gálatas 2:11-12),
la unción con aceite (Santiago 5:14),
etc.]--incluida la circuncisión--no parece haber una razón válida por la que la práctica
del bautismo en agua se considere más obligatoria en la iglesia Cristiana de hoy,
que su práctica de la circuncisión y otros ritos mosaicos.
A la vista de todo el asunto,
parece haber suficiente fundamento para concluir que la divina sabiduría permitió que
las ordenanzas tipológicas de las anteriores dispensaciones de Moisés y de Juan,
aunque efectivamente abrogadas por la muerte de Cristo en la cruz,
no fueron dejadas de lado repentinamente en el estado infantil de la iglesia,
sino de manera gradual,
conforme las mentes de los Cristianos convertidos eran capaces de comprender
más claramente el carácter espiritual de la dispensación Cristiana.

A todos aquellos cuyas mentes están tan iluminadas como para ver claramente,
que es absolutamente necesario obtener algo más que
el mero nombre o profesión externa del Cristianismo,
se les recomienda encarecidamente,
que mientras buscan ser en realidad miembros de la
iglesia de Cristo y ovejas de Su rebaño,
no intenten subir por los caminos que la sabiduría humana pueda sostener,
mediante un regreso al uso de cualquiera de los tipos
u ordenanzas de las dispensaciones anteriores,
que fueron cumplidos y abrogados por la venida y muerte de Cristo,
tal como lo declaran las Escrituras (Hebreos 9:8-11;
Colosenses 2:14-17). Porque Cristo es la puerta al verdadero redil,
o iglesia (Juan 10:9), y los que se convierten en miembros de ésta,
deben entrar por la fe en Él y sumisión al bautismo
de Su Santo Espíritu (1 Corintios 12:13).

A los que así se convierten en miembros de la verdadera iglesia de Cristo,
se les permite experimentar sus benditos privilegios.
Participan de esa comida divina que Él describe como Su carne y sangre.
Y esta comida es tan necesaria para la preservación
y crecimiento de ellos en la verdadera religión,
que Él declara: "`Si no coméis la carne del Hijo del Hombre, y bebéis su sangre,
no tenéis vida en vosotros`" (Juan 6:53).

Algunos de los que Le oyeron decir estas palabra pensaron,
como muchos profesantes Cristianos parecen pensar en el presente,
que esta declaración debía entenderse en relación
con la carne y sangre de Su cuerpo externo o material.
No obstante, nuestro Señor, misericordiosamente condescendió a corregir este error.
Que todos los que han adoptado este o algún otro significado
externo de estas palabras de Cristo que ahora nos ocupan,
reflexionen muy seriamente y acepten la explicación
que Él dio sobre este importantísimo tema.
Después de que se preguntó:
"`¿Cómo puede este darnos a comer su carne?,`" esta fue Su respuesta:
"`El Espíritu es el que da vida.`"
Entonces, si es el Espíritu el que da vida, o vivifica,
ciertamente se debe concluir que era la participación en esta influencia
vivificante de Su Santo Espíritu difundida en el alma--Él permaneciendo
en nosotros y nosotros en Él (versículo 56)--lo que Él estaba intentando
representar por medio de las frases comer Su carne y beber Su sangre,
sin lo cual no tenemos vida en nosotros.
Y, como si quisiera poner este importante punto más allá de todo riesgo de error o duda,
después de que había dicho: "`El Espíritu es el que da vida`"; inmediatamente agregó:
"`la carne para nada aprovecha;
las palabras que yo os he hablado son espíritu y son vida`" (Juan 6:63).

La doctrina del apóstol Pablo de este muy importante tema,
está en perfecta sintonía con la de su divino Maestro.
En su epístola a los corintios declara que "`el Espíritu vivifica`"
(2 Corintios 3:6). También parece (de su primera epístola a la
misma iglesia) que mucho antes de la encarnación de Cristo,
algunos de los israelitas participaron de esa comida
y bebida espirituales derivadas de Él;
porque el apóstol declara que "`todos comieron el mismo alimento espiritual,
y todos bebieron la misma bebida espiritual;
porque bebían de la roca espiritual que los seguía,
y la roca era Cristo`" (1 Corintios 10:3-4).

Si a los seguidores de Jesucristo se les hubiera
permitido comer la carne de Su cuerpo material,
es evidente por Sus propias palabras que no les habría aprovechado para nada.
Fue por la influencia vivificadora de Su Santo Espíritu,
que aquellos que creyeron en Él en aquel día fueron vivificados
y preservados "`vivos para Dios`" (Romanos 6:11). Y en el presente,
la misma influencia divina produce efectos similares en las almas de todos los que,
creyendo en la luz, vida y poder de Cristo, lo reciben a Él como su Maestro, Salvador,
Sacerdote y Rey; creyendo además, si tienen acceso a las Sagradas Escrituras,
todos esos registros sagrados que declaran acerca de los sufrimientos y muerte de Cristo,
y de los beneficios que resultan para lo humanidad.
Estos participan de la verdadera cena del Señor; como está escrito: "`He aquí,
yo estoy a la puerta +++[+++del corazón]
y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él,
y él conmigo`" (Apocalipsis 3:20). Esta comida divina es esencialmente
la misma que nuestro santo Redentor describió bajo otros términos figurativos,
como el pan que desciende del cielo y da vida al mundo;
(Juan 6:33) y como el "`agua viva,`" que será "`una fuente de agua que
salte para vida eterna`" (Juan 4:10,14) en los que beben de ella.

Aquellos que a través de la gracia divina,
experimentan un avance en la obra de regeneración,
deben reconocer siempre con gratitud esta comunicación de comida espiritual a sus almas,
en medio de las múltiples misericordias de las que son partícipes.
Al igual que la savia que permite que los pámpanos
que permanecen en la vid produzcan fruto,
así la influencia vivificadora del Espíritu de Cristo--quien es la "`vid verdadera`"
(Juan 15:1)--permite que los que permanecen como pámpanos en Él,
den los frutos del Espíritu que son "`en toda bondad,
justicia y verdad`" (Efesios 5:9). Porque bajo Su santa influencia
ellos son incitados y fortalecidos día a día a mantener,
incluso en sus asuntos temporales, una estricta adhesión a la justicia, verdad y equidad;
haciéndole a otros lo que quieren que otros les hagan a ellos.
Conforme progresa su crecimiento en la vida divina,
sus palabras y actos se ven leudados por la pureza, sinceridad,
humildad y amor Cristianos.
Ejemplifican, no sólo en sus propias familias,
sino entre todos aquellos con quienes se asocian,
la poderosa eficacia de ese nombre santo en el que han creído y han sido bautizados.

Si recordamos seriamente las solemnes declaraciones de nuestro Señor Jesucristo:
"`Si no coméis la carne del Hijo del Hombre, y bebéis su sangre,
no tenéis vida en vosotros`"; "`El que come mi carne y bebe mi sangre, en mí permanece,
y yo en él`" (Juan 6:53, 56);
y si tenemos en cuenta la clara explicación que Él condescendió darle a estas palabras,
la conclusión que debe ser aceptada con toda seguridad, por la más alta autoridad,
es que cualquiera que sea nuestra profesión religiosa--por muy
ampliamente provistas que estén nuestras mentes con el conocimiento
literal de las doctrinas y preceptos de las Sagradas Escrituras,
o por muy cargadas que estén nuestras memorias con la experiencia
registrada de hombres buenos de los tiempos antiguos y modernos,
y por muy alto que podamos pensar de nosotros, o ser estimados por otros,
por este o por cualquier otro motivo--si no participamos
de las influencias vivificadoras del Espíritu de Cristo,
no tenemos vida en nosotros; no permanecemos en Él, ni Él en nosotros; y en consecuencia,
estamos en un estado espiritual de tinieblas y muerte.
La convicción de la gran importancia de este tema, induce al escritor,
bajo lo que él confía es una medida del amor de Cristo que constriñe,
a insistir que aquellos con quienes está conectado en profesión religiosa^
footnote:[La Sociedad de Amigos.
El autor desea declarar que la Sociedad no es responsable de nada de lo
contenido en estas páginas.
{footnote-paragraph-split}
+++[+++Nota del editor:
El hecho de que Samuel Rundell se sintiera obligado a añadir esta nota,
es un triste testimonio de la decadencia de la Sociedad de Amigos durante su época.
Cualquiera que esté familiarizado con los principios y escritos de los primeros Cuáqueros,
puede testificar que la totalidad de esta publicación está en perfecto acuerdo con ellos.
Sin embargo,
a principios del siglo XIX se produjo un alarmante alejamiento de estos primeros principios,
y un retorno a gran parte de lo que los primeros
Amigos abandonaron y contra lo que testificaron.
Muchos de los Cuáqueros más influyentes de la época de Rundell,
se apoyaban mucho en la letra de la Escritura,
en el aprendizaje natural y en la fe en la aparición y muerte histórica de Cristo,
sin insistir también en la sumisión del corazón a Su bautismo interior y purificador.
Los Cuáqueros de esta descripción habían ganado tanto
el predominio en Inglaterra en la década de 1830,
que se negaron a publicar este libro.
Finalmente,
Samuel Rundell (con el estímulo y la aprobación de muchos otros) lo publicó por su cuenta,
independientemente de la Sociedad de Amigos+++]+++.]
le presten su debida atención,
así como también a los Cristianos de todas las otras denominaciones.

Habiendo tratado de señalar en las páginas anteriores los medios por los que el alma,
a través de la obediencia de la fe,
puede alcanzar la capacidad de participar de esta comida divina,
y mostrar la necesidad y beneficios de ésta,
puede ser apropiado que en el siguiente lugar se hagan algunas
observaciones adicionales con respecto a su comunicación y efectos.

La gran Cabeza de la iglesia dispensa este sustento celestial
a los miembros vivos de Su cuerpo en sus asambleas religiosas,
cuando están congregados en un estado de solemne silencio y reverente
espera delante de Él. Esto a veces sucede a través de un instrumento
(o individuo) dedicado al ministerio del evangelio,
y en otras ocasiones por el soplo directo de Su Espíritu Santo sobre sus mentes.
También se les permite disfrutar este privilegio en los momentos de sus retiros privados,
e incluso día a día,
mientras están involucrados en sus ocupaciones lícitas--si al sentir
la falta de la influencia vivificante del Espíritu de Cristo,
la buscan humildemente.

Es principalmente por este alimento divino--por este pan "`que desciende del cielo`"--que
nuestro bendito Salvador nos enseña a orar a nuestro Padre celestial diciendo:
"`El pan nuestro de cada día, dánoslo hoy.`"
Cuando son favorecidos en sus asambleas públicas
para experimentar las promesas de gracia cumplidas,
como: "`Los que esperan a Jehová tendrán nuevas fuerzas`" (Isaías 40:31),
y que donde dos o tres estén congregados en Su nombre, ahí,
Aquel que es "`espíritu vivificante`" (1 Corintios 15:45), es decir, el Señor Jesucristo,
está en medio de ellos (Mateo 18:20), pueden agradecidamente reconocer que,
aunque el ministerio a través de la intervención del hombre
es una gran bendición para la iglesia de Cristo,
y que debe ser recibido con sentimientos de gratitud de la Fuente de todo bien;
aun así es un privilegio mayor ser alimentados directamente por Él mismo,
la Cabeza santa de la iglesia y Obispo de las almas,
que a través de la intervención de sus compañeros.

La solemne declaración de nuestro santo Redentor
a la mujer de Samaria sobre el tema de la adoración,
debe, ciertamente, causar una impresión profunda y llena de asombro,
sobre las mentes de todos los que profesan postrarse delante del Altísimo.
"`Dios es Espíritu; y los que le adoran,
en espíritu y en verdad es necesario que adoren.`"
Y otra vez dijo: "`Nadie viene al Padre,
sino por mí,`" y "`separados de mí nada podéis hacer.`"
Cuán necesario debe ser, entonces, con el fin de realizar esta adoración,
que la mente sea llevada a un estado de total humillación--inclinada
bajo un verdadero sentido de su gran debilidad,
de sus muchas necesidades y completa indignidad--acompañada por
la convicción de la perfecta pureza de ese Ser Todopoderoso,
cuya sagrada presencia es inaccesible excepto a través de nuestro santo Mediador,
el Señor Jesucristo.
Quizás se pueda decir,
que no hay otra ocupación en la que la mente religiosamente
ejercitada esté tan completamente penetrada por esos sentimientos,
como en la espera silenciosa en Dios en las asambleas para la adoración pública.

Pero aunque Cristo siempre está en alguna medida presente con aquellos,
que por el bautismo de Su Espíritu Santo, son miembros de Su iglesia, aun así,
según la experiencia de muchos que son de esta descripción,
Él a menudo se complace en retener de ellos por un tiempo--en sus asambleas religiosas,
así como también en otros momentos--esa mayor comunicación de Su poder y vida que es
necesaria para capacitarlos para realizar el acto solemne de la adoración divina.
Sí, por un propósito sabio y bondadoso,
Él a menudo les permite sentir cuán débiles son por sí mismos,
y lo absolutamente insuficientes que son por medio de sus propias fuerzas,
de resistir los esfuerzos del adversario de sus almas.
Este adversario, al excitar la propensión natural a ocuparse de las cosas terrenales,
o al presentarle a la imaginación de la criatura
ideas relativas a la adoración o a la doctrina,
con frecuencia se esfuerza por apartar sus mentes de esa negación al yo--la
subyugación de sus propias voluntades y sabiduría--que es necesaria para
esperar pacientemente en Dios en el ejercicio de la fe y del amor.

Pero aunque Él, el buen '`Pastor y Obispo de las almas`' (1 Pedro 2:25),
permita que los humildes creyentes en Él sean así tratados y probados, no los abandona.
En Su debido tiempo (por el que ellos reverentemente esperan
con ferviente deseo) la influencia vivificadora y purificadora
de Su Espíritu Santo les imparte un nuevo vigor a sus almas,
y así fortalecidos,
superan los impedimentos--de cualquier tipo--que les han obstruido
la entrada "`al trono de la gracia`" (Hebreos 4:16),
y son capacitados para '`acercarse en plena certidumbre de fe.`'
(Hebreos 10:22) La adoración ofrecida así en las asambleas religiosas,
ya sea acompañada de un ministerio de predicación, oración, o alabanza,
(ofrecida en obediencia a la voluntad de la gran Cabeza de la iglesia,
directamente comunicada a aquellos miembros que Él vea conveniente emplear
en Su servicio) o que en obediencia a la misma voluntad santa,
consista enteramente en respiraciones silenciosas^
footnote:[No debe suponerse que todos los que practican el sentarse
en silencio en las asambleas para la adoración pública,
se benefician de la manera descrita anteriormente.
Sólo la mente despierta--la mente en la que la obra de regeneración ha
comenzado en cierto grado--es capaz de esperar verdaderamente en Dios
en silencio bajo un ejercicio de fe y amor hacia Él. Sin embargo,
hay motivos para creer que en numerosos casos,
individuos que previamente han mostrado poca o ninguna
preocupación por la salvación de su alma,
habiendo entrado en una asamblea religiosa silenciosa (algunos
de ellos probablemente por mera curiosidad) han sido despertados,
y sus mentes grandemente abatidas por el poder divino;
aunque no se haya pronunciado una palabra.
Y esta visitación del amor del Redentor ha demostrado ser
el comienzo de la obra eficaz de Su gracia en sus almas.]
que se levantan de las almas vivificadas en un estado
de reverente postración delante del trono de gracia;
cualquier que sea el caso, esta adoración no deja de tener la aceptación divina.

Aunque muchos individuos en quien la obra de regeneración ha comenzado,
y están en la práctica de esperar en Dios en las asambleas de la adoración pública,
no siempre reciben tal provisión de comida espiritual como
la estimación de sus propias necesidades los llevan a esperar;
aun así, éstos no deberían desanimarse.
Que consideren adecuadamente, que el Señor sabe mejor que ellos qué es mejor para ellos.
Él sabe qué conducirá al progreso de esa gran obra que ha comenzado en sus almas.
Por un propósito sabio y benigno,
Él introduce a Sus hijos en un estado de pobreza de espíritu;
la tendencia de esta disciplina es incrementar la
fe de ellos y establecerlos más firmemente en Él,
el "`fundamento firme,`" "`la Roca de los siglos.`"

Por lo tanto, ustedes que tienen hambre y sed del pan y del vino de vida,
no se desanimen por la aparente pequeñez de la porción que a veces,
incluso con frecuencia, se les dispensa.
Figurativamente hablando,
si no es más que una migaja de pan o una gota de "`agua viva,`" aun así,
si la reciben con agradecimiento hallarán que es suficiente para la necesidad presente;
suficiente para fortalecerlos a continuar confiando en el Señor y esperando en Él en fe,
y con una esperanza viva en Su bondad y misericordia.
Y cada vez que observen estos efectos,
deben estimarlos como una evidencia de que por la
bondadosa consideración de su Padre celestial,
se les ha brindado una porción de ayuda y sustento divinos.
¡Cuán precioso es para el alma atribulada,
el reavivamiento de esta fe y de esta esperanza,
después de haber experimentado mucho esfuerzo y conflicto mental en las asambleas religiosas
o en retiros privados! ¡Alabado sea el santo nombre del Señor por todas Sus misericordias,
de las que participan aquellos que están ocupados (aunque frecuentemente
bajo un sentimiento de muchos desalientos y debilidades) en buscar
la habilidad de adorarlo en Espíritu y en verdad!
