== Capítulo IV. Observaciones finales

Al repasar los temas a los que se hacen referencia en estas páginas,
el escritor se inclina a decir un poco más de algunos de ellos,
especialmente de este tan importante:
Los beneficios para la humanidad que resultan de los sufrimientos
y muerte de nuestro bendito Salvador Jesucristo en la cruz.
Esto es seguido por algunas observaciones adicionales
con respecto a la adoración y al ministerio,
con una exhortación a los profesantes Cristianos.

Las Escrituras declaran que la '`Palabra que estaba en el principio con Dios, y era Dios,
se hizo (o tomó) carne`' (Juan 1:1-14). "`Por cuanto
los hijos participaron de carne y sangre,
Él también participó de lo mismo,
para destruir por medio de la muerte al que tenía el imperio de la muerte, esto es,
al diablo`" (Hebreos 2:14). "`Él es la propiciación por nuestros pecados;
y no solamente por los nuestros,
sino también por los de todo el mundo`" (1 Juan 2:2).
Él sufrió la muerte en la cruz y fue sepultado.
Al tercer día resucitó de entre los muertos y ascendió al cielo,
donde glorificado con el Padre, es nuestro Mediador e Intercesor con Él.

Al proceder a describir más detalladamente los beneficios
para la humanidad que resultan de la muerte de Cristo,
los sentimientos del escritor sobre este tema están bien
expresados en la Apología de la Verdadera Divinidad Cristiana,
de Robert Barclay, e inserta la siguiente selección de esa obra.

Por tanto, nosotros consideramos nuestra redención en un doble aspecto o estado,
ambos perfectos en su propia naturaleza, aunque en su aplicación a nosotros,
uno no puede ser sin el aspecto del otro, como veremos.

El primero es la redención realizada y cumplida por
Cristo a favor de nosotros en Su cuerpo crucificado,
fuera de nosotros.
El otro es la redención forjada por Cristo dentro de nosotros,
la cual no es menos apropiadamente llamada y considerada redención que la anterior.
El primero es aquel, por medio del cual, el hombre tal como está en la caída,
es colocado en la capacidad de salvación, y se le comunica una medida de ese poder,
virtud, espíritu, vida y gracia que estaban en Cristo Jesús--que,
como un don gratuito de Dios,
es capaz de vencer y desarraigar la semilla del mal con la que
estamos naturalmente leudados en la caída. El segundo es ese,
por el que experimentamos y conocemos esta redención pura y perfecta en nosotros mismos,
purificándonos, limpiándonos y redimiéndonos del poder de la corrupción,
y llevándonos a una unidad, favor y comunión con Dios.

Por el primero de estos dos, nosotros, que estábamos perdidos en Adán;
sumidos en la semilla amarga y corrupta;
incapaces por nosotros mismos de hacer algo bueno, sino naturalmente unidos al mal;
prestos y propensos a toda iniquidad;
siervos y esclavos del poder y del espíritu de las tinieblas, somos,
a pesar de todo esto, reconciliados con Dios hasta tal punto por la muerte de su Hijo,
incluso siendo enemigos, que somos puestos en capacidad de salvación,
y se nos ofrecen las buenas noticias del Evangelio de paz,
de que Dios se reconcilia con nosotros en Cristo, y por tanto,
nos llama e invita a Él. Es en este sentido que entendemos las siguientes Escrituras:
"`Aboliendo en su carne las enemistades`"; "`Él nos amó primero`";
"`viéndonos en nuestra sangre, Él nos dijo: ¡Vive!`";
"`llevó él mismo nuestros pecados en su cuerpo sobre el madero`";
"`porque también Cristo padeció una sola vez por los pecados,
el justo por los injustos`"; etc.
(Efesios 2:15; 1 Juan 4:19; 1 Pedro 2:22, 24; 3:18)

Por el segundo, experimentamos esa capacidad llevada a la acción,
por la que al recibir y no resistir la compra de Su muerte, (a saber, la Luz,
Espíritu y Gracia de Cristo revelado en nosotros)
experimentamos y poseemos una redención real,
verdadera e interna del poder y dominio del pecado,
y así llegamos a ser verdadera y realmente redimidos, justificados y hechos justos,
y a una unión y comunión experimental con Dios.
Así, Él "`se dio a sí mismo por nosotros para redimirnos de toda iniquidad,
y purificar para sí un pueblo peculiar`" (Tito 2:14);
y así nosotros podemos "`conocerle a él, y el poder de su resurrección,
y la comunión de sus padecimientos,
siendo hecho conforme a su muerte`" (Filipenses 3:10).
Esto último sigue lo primero en orden,
y es una consecuencia de él, procede de él, tal como un efecto procede de su causa.
Así entonces,
dado que nadie puede disfrutar lo último sin que lo primero
se haya establecido (siendo ésta la voluntad de Dios),
tampoco nadie puede participar verdaderamente de lo primero,
a menos que experimente lo último.
Por lo tanto, para nosotros, ambos son causa de nuestra justificación.

--Apología, Prop.
7, Sec.3

Es evidente por el testimonio de la Escritura,
que es absolutamente necesario para nuestra completa redención,
que creamos individualmente en la luz divina o Espíritu de Cristo,
y que mediante la sumisión a Su bautismo,
experimentemos la obra de regeneración de nuestras almas.
Por lo tanto,
cuán deseable es que entre todos los profesantes Cristianos (como ya ha sido sugerido),
no se abracen doctrinas,
ni se establezca ni practique ninguna ordenanza o
institución relativa al ministerio y adoración,
la tendencia de lo cual sea desviar la atención de ellos de este Maestro interno,
o en algún grado, obstruir o restringir Su influencia y operación en el alma.
Una atenta lectura del Nuevo Testamento mostrará,
que uno de los principales objetivos del ministerio de Jesucristo,
y también de Sus apóstoles,
era volver la atención de las personas a este don divino
como su maestro y guía en el camino hacia la felicidad eterna.
Y ciertamente,
este debe ser el principal objetivo en la visión de cada
ministro profesante de Cristo en el día presente.
Porque la religión Cristiana es, en sí misma,
la misma ahora que fue en la época apostólica.
Sin embargo, tristemente,
grande es la degeneración de su pureza original entre muchos de sus profesantes,
no sólo con respecto a la conducta y manera de vivir,
sino también con respecto a la doctrina y adoración.

Los verdaderos creyentes en Cristo,
después de su conversión y la remisión de sus pecados pasados a través de Su sangre,
todavía están expuestos en su interacción con el mundo (cuando la vigilancia diaria
en oración no es plenamente mantenida) a contraer contaminación de su espíritu,
y también de la carne y del diablo.
Cuando esta contaminación es recibida--por mínima que sea--no
puede escapar la detección de Aquel que ve todas las cosas.
En cualquier grado que haya prevalecido, tiende a obstruir el acceso del alma a Dios,
quien es un Ser de infinita pureza y santidad.
Ahora bien, la gran Cabeza de la iglesia, el Sumo Sacerdote y Obispo de las almas,
contempla el estado de cada individuo en las asambleas religiosas,
y no deja (cuando lo ve oportuno) de dispensar a cada persona según su necesidad,
quien en el ejercicio de fe y amor viene a Él. Él
parte el pan de vida para los puros de corazón,
y en Su abundante misericordia les da arrepentimiento y contrición de alma,
a los que por falta de vigilancia, han contraído algún grado de contaminación,
y así '`purifica los corazones de mala conciencia`' (Hebreos 10:22).

Así, pues, se confirma la misericordiosa declaración de nuestro Señor:
"`Porque donde están dos o tres congregados en mi nombre, +++[+++y por consiguiente,
también cuando un gran grupo mayor está congregado]
allí estoy Yo en medio de ellos`" (Mateo 18:20). Porque estas palabras
de nuestro santo Redentor no son sonidos sin sentido;
son verdades definitivas y muy ciertas.
¡Qué bendito privilegio es entonces,
que una asamblea religiosa pueda experimentar la presencia
vivificadora de Cristo revelado en y entre ellos!
Pero debe tenerse presente siempre que este gran privilegio es otorgado a aquellos,
y solamente a aquellos, que están reunidos en Su nombre.
Su nombre, como ya ha sido observado,
significa o hace referencia a Sus atributos divinos, a saber, Su poder, vida, luz, etc.

A fin de que podamos participar de este gran privilegio,
no debemos olvidar el mandamiento de nuestro santo Redentor a Sus discípulos:
"`Y lo que a vosotros digo, a todos lo digo: Velad.`"
Y otra vez: "`Velad y orad, para que no entréis en tentación`" (Marcos 13:37;
Mateo 26:41). Es, en efecto,
una tarea muy necesaria a guardar en el transcurso de nuestra
conducta y nuestras interacciones diarias con los hombres;
pero en ninguna ocasión la práctica de vigilar es más necesaria,
que en las asambleas de adoración pública.
Porque hay razones para creer que el enemigo de todo bien,
se esfuerza por todos los medios en su poder para evitar
la adoración al Todopoderoso Dios en espíritu y en verdad;
y la mente humana por su propia fuerza es totalmente incompetente de resistir sus esfuerzos.

"`Mas la hora viene, y ahora es,
cuando los verdaderos adoradores adorarán al Padre en espíritu y en verdad;
porque también el Padre tales adoradores busca que le adoren`" (Juan 4:23).
Esta declaración de Jesucristo de este importante tema,
ofrece suficiente terreno para concluir,
que es consistente con la voluntad de nuestro Padre celestial que
esta adoración espiritual y pura prevalezca en todo lugar.
Por lo tanto,
cuando nos reunimos con el propósito de la adoración divina--para ser
preservados de la oposición a la voluntad divina en este asunto--es indispensable
nuestra obediencia constante e implícita al mandamiento de nuestro Señor
de que "`todos,`" de toda denominación en Su iglesia militante,
deben "`velar.`"
Esta diligente vigilancia es necesaria,
para que las súplicas de nuestras almas asciendan
a Él bajo la influencia de Su Espíritu Santo,
y para que no entremos en ninguna tentación del enemigo--incluida la tentación de predicar,
o audiblemente orar o cantar,
antes de que la influencia vivificadora del Espíritu de Cristo
se sienta claramente dirigiendo hacia alguno de estos actos.

Puede entenderse que el deber de vigilar también incluye el deber de esperar en Dios;
y si este deber es pacientemente guardado,
existe la seguridad misericordiosa de que el resultado será
la renovación de fuerzas (Isaías 40:31). Así vigorizados,
los verdaderos creyentes--mediante la amorosa bondad y fuerza del Señor--vencerán las
tentaciones del adversario de sus almas y podrán adorar al Padre de los espíritus,
en espíritu y en verdad.
Esta adoración en solemne y reverente silencio puede ser seguida,
tan a menudo como a la gran Cabeza de la iglesia le plazca dirigir,
por el ministerio de predicación, oración y alabanza.
Y esta dirección comunicada por la directa influencia de Su Santo Espíritu,
en el momento y manera que Él considere apropiado darla en las asambleas religiosas,
será claramente entendida por aquellos individuos (si están debidamente
vigilantes y atentos) a quienes Él le plazca confiar el don del ministerio.
Él también les proporcionará los suministros necesarios de esa
"`sabiduría que es de arriba`" para la edificación de Su iglesia.
En la medida que su dependencia sea colocada en esa sabiduría y no en la propia,
sólo entonces se cumplirá cabalmente la dirección apostólica:
"`Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra,
ministre conforme al poder que Dios da,
para que en todo sea Dios glorificado por Jesucristo`" (1 Pedro 4:11).

En la adoración divina,
de acuerdo con los varios textos de las Sagradas Escrituras referentes a este tema,
la influencia vivificadora del Espíritu de Cristo debe ser considerada
como el único verdadero manantial para la acción. No debe permitirse
que la voluntad y sabiduría del hombre dominen,
o tomen el mando,
sino que deben ser completamente mantenidas en subordinación.
El tenor general de esas declaraciones y promesas que las
Escrituras sostienen relativas a Cristo y a Su Santo Espíritu,
Lo describen como dado a la humanidad para ser su Señor; su Líder, su Guía, su Pastor,
su Sumo Sacerdote, etc.
(Juan 13:13; Isaías 55:4; Juan 10:4; Juan 16:13; Hebreos 2:17) Ahora,
estas frases transmiten la idea de precedencia, de dirección,
de ir delante--pero no de ir detrás. En consecuencia,
encontramos que cuando nuestro Señor se describe
a Sí mismo como "`el buen Pastor,`" dice:
"`Y cuando ha sacado sus propias ovejas, va delante de ellas; y las ovejas le siguen,
porque conocen su voz`" (Juan 10:4). "`El buen Pastor`" entonces '`saca sus propias
ovejas`' en todos sus servicios religiosos--en asambleas públicas y en otras ocasiones.

Por tanto,
si se admite que la adoración que es en espíritu y en verdad es realizada
únicamente bajo la influencia vivificadora y guía del Espíritu de Cristo;
les corresponde a todos los profesantes del Cristianismo considerar muy seriamente,
si están llevando a cabo esta adoración cuando en sus asambleas públicas
comienzan sus servicios religiosos según una forma previamente prescrita,
o cuando sus ministros dependen de su propia sabiduría para
el suministro de material para sus sermones y oraciones.
Si su adoración comienza de esta forma y es realizada de esa manera--o para aquellos
profesantes Cristianos que no usan ninguna forma de adoración prescrita,
si algunos de sus ministros no tienen cuidado de esperar
reverentemente ese "`poder que Dios da`" (1 Pedro 4:11),
y si se atreven a predicar u orar en sus asambleas sin este
requerimiento esencial--debería ser tema de grave consideración,
si en todos estos casos están procediendo sin el único Guía y Líder seguro,
y en Su lugar lo están sustituyendo con otro líder, es decir, la sabiduría humana.
Porque, en efecto, a partir del testimonio de las Sagradas Escrituras,
no tenemos fundamento para esperar que el Espíritu
de Cristo nos vaya a seguir con su influencia vivificadora,
cuando nos hemos puesto a nosotros mismos bajo la dirección de
nuestra propia voluntad y sabiduría al comenzar a predicar,
orar o cantar en nuestras asambleas religiosas antes de sentir
la influencia vivificadora del Espíritu de Cristo para impulsar
y liderar la realización de cualquiera de estos actos.

No obstante,
lejos está del escritor asignar límites al amor y misericordia de nuestro Señor Jesucristo.
Cree plenamente que en muchos casos, donde se encuentra rectitud y sinceridad de corazón,
nuestro santo Redentor bondadosamente condesciende a hacer que los servicios religiosos,
que son en algún grado del carácter ya descrito,
sean eficaces para despertar a los inconversos y convencerlos
del peligro de vivir en el olvido de Dios,
y excitar en sus corazones un sentimiento vivo de su necesidad de un Salvador.
Sin embargo,
es de gran importancia que esta misericordiosa condescendencia de infinita bondad,
no se sostenga como un argumento para obstruir el recibimiento
y obediencia a manifestaciones adicionales de la luz divina,
que puedan permitirles discriminar más claramente
entre esa adoración que es en espíritu y en verdad,
y aquellas actuaciones a las que el apelativo "`culto
voluntario`" es en algún grado aplicable.

Cuando consideramos que el bienestar en esta vida
y la felicidad eterna en el más allá de cada individuo,
depende de que se convierta en un verdadero Cristiano
y no en uno meramente nominal-- entonces,
el tema claramente parece ser de la mayor importancia.
Porque como dijo nuestro bendito Salvador:
"`¿Qué aprovechará al hombre si ganare todo el mundo, y perdiere su alma?`"
Que cada profesante Cristiano sea animado a no colocar su
dependencia en ser un miembro de cualquier comunidad religiosa,
o en la práctica de unirse a cualquier forma externa de adoración u observancia ceremonial.
Sino más bien, que con un grado de ansiedad equivalente a la importancia del tema,
busque un conocimiento experimental del poder de Dios internamente revelado,
para que mediante la sumisión a su humillante operación,
'`todo monte y collado (de auto-exaltación) sea bajado`' (Lucas 3:5), y de esa manera,
todo obstáculo para ir a Cristo y participar de la salvación que es por Él,
sea efectivamente removido.

Con este importante objetivo en mente,
apliquémonos una porción de la doctrina referida en las páginas anteriores.
Dios, en Su infinito amor a la humanidad, ha declarado respecto a Cristo:
"`Te di por luz de las naciones,
para que seas Mi salvación hasta lo postrero de la
tierra`" (Isaías 49:6). Y nuestro santo Redentor,
refiriéndose a este don divino y describiendo la
causa de la condenación de los que perecen dijo:
"`Y ésta es la condenación; que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.`"
Por lo tanto, para que no nos entreguemos a esta condenación por no amar,
sino menospreciar y rechazar a Cristo en Su manifestación como la Luz,
hagamos individualmente un examen de corazón por medio de
la aplicación concienzuda de las siguientes preguntas.

¿Crees en Cristo, en referencia a Su aparición espiritual en tu propia alma?
(2 Corintios 13:5) En el lenguaje metafórico de las Escrituras,
¿le has abierto la puerta de tu corazón a Él, cuando,
mediante las secretas convicciones de Su santa Luz y Espíritu,
ha tocado ahí para que lo dejes entrar?
(Apocalipsis 3:20) ¿Has recibido a Cristo de esta manera,
para que sea tu líder (Isaías 55:4),
tu bautizador (Mateo 3:11) y tu sumo sacerdote y rey?
(Hebreos 2:17; Isaías 33:22) ¿Es tu preocupación diaria el obedecerlo en todas las cosas,
evitando en cada parte de tu conducta y conversación
lo que la luz manifiesta como malo (Juan 3:20-21),
negándote a ti mismo y tomando la cruz con respecto a cada
búsqueda y gratificación que el divino Monitor no permita,
por muy fervientemente que lo pidan tus inclinaciones y deseos naturales?
(Lucas 9:23) Y finalmente, ¿experimentas,
a través de la sumisión a la operación bautismal de Su Espíritu Santo,
la obra de regeneración iniciada y gradualmente progresando en tu alma?
(Juan 3:3)

Promover esta gran obra de reforma entre los Cristianos profesantes de todas las denominaciones,
es el objetivo que el autor tiene en mente.
Fervientemente desea que las visitas del amor y misericordia divinos que despiertan
el alma sean ampliamente abrazadas--para que sea grande el número de aquellos,
que al sentir la carga del pecado y de su necesidad de un Salvador,
y bajo la convicción de que la apariencia de piedad sin el poder no puede salvarlos,
estén dispuestos a aceptar la misericordiosa invitación:
"`Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.
Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón;
y hallaréis descanso para vuestras almas.`"
En la medida que prevalezca la preocupación general de ir a Cristo de
esta manera--de someterse a Su yugo y de aprender de Él y ser bautizados
por Él--el fruto de Su Santo Espíritu se producirá abundantemente.
Entonces, el genuino Cristianismo brillará de nuevo con su antigua belleza;
el nombre del Todopoderoso Dios será glorificado por la
consecuente conducta y conversación de los Cristianos profesantes;
y en sus asambleas religiosas,
ya no se permitirá que la voluntad ni la sabiduría del hombre dominen, sino que,
al ser guardadas en debida subordinación, la luz, vida,
poder y sabiduría eternos de nuestro Dios serán exaltados en dominio sobre todos.

'`Así, pues, Padre Santo, venga Tu reino, hágase Tu voluntad en la tierra,
como es hecha en el cielo.`'
